# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SCORMCloudContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content_id",
                    models.CharField(
                        blank=True,
                        help_text="External content identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="generic",
                        help_text="Type of content this SCORM package is associated with",
                        max_length=50,
                    ),
                ),
                (
                    "registration_prefix",
                    models.CharField(default="LMS_", max_length=50),
                ),
                ("passing_score", models.IntegerField(default=80)),
                ("requires_passing_score", models.BooleanField(default=True)),
                ("tracking_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "SCORM Cloud Content",
                "verbose_name_plural": "SCORM Cloud Contents",
            },
        ),
        migrations.CreateModel(
            name="SCORMDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cloud_id", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("cookies", "Cookie Based"),
                            ("url", "URL Parameters"),
                            ("form", "Form Post"),
                            ("basic", "HTTP Basic"),
                            ("oauth", "OAuth"),
                        ],
                        default="cookies",
                        max_length=50,
                    ),
                ),
                ("hash_user_info", models.BooleanField(default=False)),
                ("additional_settings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SCORMDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cloud_id", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("allow_new_registrations", models.BooleanField(default=True)),
                (
                    "registration_cap",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of registrations allowed",
                        null=True,
                    ),
                ),
                ("registration_count", models.IntegerField(default=0)),
                ("last_reset_date", models.DateTimeField(blank=True, null=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "instanced",
                    models.BooleanField(
                        default=True, help_text="Enable versioning support"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("tracking_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SCORM Dispatch",
                "verbose_name_plural": "SCORM Dispatches",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SCORMPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cloud_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "version",
                    models.CharField(
                        choices=[("1.2", "SCORM 1.2"), ("2004", "SCORM 2004")],
                        default="1.2",
                        max_length=50,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("launch_url", models.URLField(max_length=1000)),
                ("entry_url", models.URLField(blank=True, max_length=1000)),
                (
                    "use_frameset",
                    models.BooleanField(
                        default=True, help_text="Use frameset instead of iframe"
                    ),
                ),
                (
                    "launch_mode",
                    models.CharField(
                        choices=[
                            ("iframe", "Embed in iframe"),
                            ("window", "Open in same window"),
                            ("popup", "Open in popup window"),
                        ],
                        default="window",
                        help_text="How to open SCORM content",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "SCORM Package",
                "verbose_name_plural": "SCORM Packages",
            },
        ),
        migrations.CreateModel(
            name="SCORMRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completion_status",
                    models.CharField(default="incomplete", max_length=20),
                ),
                ("success_status", models.CharField(default="unknown", max_length=20)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_time", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("progress_data", models.JSONField(blank=True, default=dict)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="scorm_cloud.scormpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "SCORM Registration",
                "verbose_name_plural": "SCORM Registrations",
            },
        ),
    ]
