# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scorm_cloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scormregistration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scorm_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scormpackage",
            name="default_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_packages",
                to="scorm_cloud.scormdestination",
            ),
        ),
        migrations.AddField(
            model_name="scormdispatch",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="scorm_cloud.scormdestination",
            ),
        ),
        migrations.AddField(
            model_name="scormdispatch",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="scorm_cloud.scormpackage",
            ),
        ),
        migrations.AddField(
            model_name="scormcloudcontent",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloud_contents",
                to="scorm_cloud.scormpackage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scormdispatch",
            unique_together={("destination", "package")},
        ),
        migrations.AlterUniqueTogether(
            name="scormcloudcontent",
            unique_together={("content_type", "content_id")},
        ),
    ]
