# Generated by Django 4.2.24 on 2025-09-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorm_cloud', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormcloudcontent',
            name='scorm_package_id',
            field=models.CharField(blank=True, help_text='SCORM Cloud package ID for direct reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scormcloudcontent',
            name='package',
            field=models.ForeignKey(blank=True, help_text='SCORM package associated with this content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_contents', to='scorm_cloud.scormpackage'),
        ),
    ]
