# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("branch_portal", "0001_initial"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="course",
            field=models.ForeignKey(
                help_text="Course being ordered",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                help_text="Order this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="branch_portal.order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                help_text="Branch associated with this order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="branches.branch",
            ),
        ),
    ]
