# Generated by Django 3.2.25 on 2025-10-04 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20251004_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('1.2', 'SCORM 1.2'), ('2004', 'SCORM 2004')], default='1.2', max_length=10)),
                ('identifier', models.CharField(help_text='Package identifier from manifest', max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('package_file', models.FileField(help_text='Original SCORM ZIP package', upload_to='scorm_packages/%Y/%m/')),
                ('extracted_path', models.CharField(help_text='Path to extracted SCORM content', max_length=500)),
                ('launch_url', models.CharField(help_text='Relative path to launch file (index.html, story.html, etc.)', max_length=500)),
                ('manifest_data', models.JSONField(default=dict, help_text='Parsed manifest.xml data')),
                ('mastery_score', models.DecimalField(blank=True, decimal_places=2, help_text='Mastery score from manifest', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_package', to='courses.topic')),
            ],
            options={
                'verbose_name': 'SCORM Package',
                'verbose_name_plural': 'SCORM Packages',
                'db_table': 'scorm_package',
            },
        ),
        migrations.CreateModel(
            name='ScormAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('lesson_status', models.CharField(choices=[('not_attempted', 'Not Attempted'), ('incomplete', 'Incomplete'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_attempted', max_length=20)),
                ('completion_status', models.CharField(default='incomplete', max_length=20)),
                ('success_status', models.CharField(default='unknown', max_length=20)),
                ('score_raw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_min', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('score_max', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True)),
                ('score_scaled', models.DecimalField(blank=True, decimal_places=3, help_text='Scaled score (0-1)', max_digits=4, null=True)),
                ('total_time', models.CharField(default='0000:00:00.00', help_text='Total time in SCORM format (hhhh:mm:ss.ss)', max_length=50)),
                ('session_time', models.CharField(default='0000:00:00.00', help_text='Session time in SCORM format', max_length=50)),
                ('lesson_location', models.CharField(blank=True, help_text='Bookmark/location in the course', max_length=1000)),
                ('suspend_data', models.TextField(blank=True, help_text='Suspend data for resuming')),
                ('entry', models.CharField(default='ab-initio', help_text='Entry mode (ab-initio, resume)', max_length=20)),
                ('exit_mode', models.CharField(blank=True, max_length=20)),
                ('cmi_data', models.JSONField(default=dict, help_text='Complete CMI data model storage')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scorm_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scorm.scormpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SCORM Attempt',
                'verbose_name_plural': 'SCORM Attempts',
                'db_table': 'scorm_attempt',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'scorm_package', 'attempt_number')},
            },
        ),
    ]
