# Generated by Django 3.2.25 on 2025-10-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCORMAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_status', models.CharField(default='not attempted', help_text='SCORM lesson status (not attempted, incomplete, completed, passed, failed, browsed)', max_length=50)),
                ('completion_status', models.CharField(default='unknown', help_text='SCORM 2004 completion status', max_length=50)),
                ('success_status', models.CharField(default='unknown', help_text='SCORM 2004 success status', max_length=50)),
                ('score_raw', models.FloatField(blank=True, help_text='Raw score', null=True)),
                ('score_min', models.FloatField(blank=True, help_text='Minimum score', null=True)),
                ('score_max', models.FloatField(blank=True, help_text='Maximum score', null=True)),
                ('score_scaled', models.FloatField(blank=True, help_text='Scaled score (0-1)', null=True)),
                ('lesson_location', models.CharField(blank=True, help_text='Bookmark/location in content', max_length=1000)),
                ('suspend_data', models.TextField(blank=True, help_text='Suspend data for resuming')),
                ('total_time', models.CharField(default='0000:00:00.00', help_text='Total time spent (SCORM timeinterval format)', max_length=50)),
                ('session_time', models.CharField(default='0000:00:00.00', help_text='Current session time', max_length=50)),
                ('learner_response', models.TextField(blank=True)),
                ('learner_comments', models.TextField(blank=True)),
                ('cmi_data', models.JSONField(blank=True, default=dict, help_text='Complete CMI data object')),
                ('exit_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('attempt_number', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'SCORM Attempt',
                'verbose_name_plural': 'SCORM Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SCORMPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Package title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('version', models.CharField(blank=True, help_text='Package version', max_length=50)),
                ('package_type', models.CharField(choices=[('SCORM_12', 'SCORM 1.2'), ('SCORM_2004', 'SCORM 2004'), ('XAPI', 'xAPI/Tin Can'), ('ARTICULATE_RISE', 'Articulate Rise 360'), ('ARTICULATE_STORYLINE', 'Articulate Storyline'), ('ADOBE_CAPTIVATE', 'Adobe Captivate'), ('ISPRING', 'iSpring'), ('LECTORA', 'Lectora'), ('HTML5', 'Generic HTML5'), ('AUTO', 'Auto-detect')], default='AUTO', help_text='Type of SCORM package', max_length=50)),
                ('package_file', models.FileField(help_text='Original SCORM package ZIP file', upload_to='scorm/packages/%Y/%m/%d/')),
                ('extracted_path', models.CharField(blank=True, help_text='Path to extracted package content in S3', max_length=500)),
                ('launch_file', models.CharField(blank=True, help_text='Main launch file (e.g., index.html, story.html)', max_length=500)),
                ('identifier', models.CharField(blank=True, max_length=500)),
                ('manifest_data', models.JSONField(blank=True, default=dict, help_text='Parsed manifest data from imsmanifest.xml')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether package has been extracted and processed')),
                ('processing_error', models.TextField(blank=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorm_packages_created', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, help_text='Associated course topic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorm_packages', to='courses.topic')),
            ],
            options={
                'verbose_name': 'SCORM Package',
                'verbose_name_plural': 'SCORM Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SCORMObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='unknown', help_text='passed, failed, completed, incomplete, browsed, not attempted, unknown', max_length=50)),
                ('success_status', models.CharField(blank=True, max_length=50)),
                ('completion_status', models.CharField(blank=True, max_length=50)),
                ('score_raw', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('score_scaled', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('progress_measure', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='scorm.scormattempt')),
            ],
            options={
                'verbose_name': 'SCORM Objective',
                'verbose_name_plural': 'SCORM Objectives',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SCORMInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_id', models.CharField(max_length=255)),
                ('interaction_type', models.CharField(blank=True, help_text='true-false, choice, fill-in, long-fill-in, matching, performance, sequencing, likert, numeric, other', max_length=50)),
                ('objectives', models.JSONField(blank=True, default=list, help_text='Associated learning objectives')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('learner_response', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('correct_response', models.TextField(blank=True)),
                ('weighting', models.FloatField(blank=True, null=True)),
                ('latency', models.CharField(blank=True, help_text='Time taken to complete interaction', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='scorm.scormattempt')),
            ],
            options={
                'verbose_name': 'SCORM Interaction',
                'verbose_name_plural': 'SCORM Interactions',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SCORMEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Initialize, SetValue, GetValue, Commit, Terminate, etc.', max_length=50)),
                ('element', models.CharField(blank=True, max_length=500)),
                ('value', models.TextField(blank=True)),
                ('result', models.CharField(default='true', max_length=50)),
                ('error_code', models.CharField(default='0', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scorm.scormattempt')),
            ],
            options={
                'verbose_name': 'SCORM Event',
                'verbose_name_plural': 'SCORM Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scorm.scormpackage'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorm_attempts', to='courses.topic'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['created_at'], name='scorm_scorm_created_f36865_idx'),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['is_active', 'is_processed'], name='scorm_scorm_is_acti_3ed2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['topic'], name='scorm_scorm_topic_i_0d5931_idx'),
        ),
        migrations.AddIndex(
            model_name='scormobjective',
            index=models.Index(fields=['attempt', 'objective_id'], name='scorm_scorm_attempt_e3dad6_idx'),
        ),
        migrations.AddIndex(
            model_name='scorminteraction',
            index=models.Index(fields=['attempt', 'timestamp'], name='scorm_scorm_attempt_967be9_idx'),
        ),
        migrations.AddIndex(
            model_name='scorminteraction',
            index=models.Index(fields=['interaction_id'], name='scorm_scorm_interac_7c946c_idx'),
        ),
        migrations.AddIndex(
            model_name='scormevent',
            index=models.Index(fields=['attempt', 'timestamp'], name='scorm_scorm_attempt_a1db98_idx'),
        ),
        migrations.AddIndex(
            model_name='scormevent',
            index=models.Index(fields=['event_type'], name='scorm_scorm_event_t_1ca4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='scormevent',
            index=models.Index(fields=['session_id'], name='scorm_scorm_session_e25bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='scormattempt',
            index=models.Index(fields=['user', 'package'], name='scorm_scorm_user_id_d4323e_idx'),
        ),
        migrations.AddIndex(
            model_name='scormattempt',
            index=models.Index(fields=['started_at'], name='scorm_scorm_started_889cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='scormattempt',
            index=models.Index(fields=['lesson_status'], name='scorm_scorm_lesson__368f41_idx'),
        ),
        migrations.AddIndex(
            model_name='scormattempt',
            index=models.Index(fields=['topic'], name='scorm_scorm_topic_i_ae8aa2_idx'),
        ),
    ]
