# Generated by Django 3.2.25 on 2025-10-16 10:45

from django.db import migrations, models
import scorm.models
import scorm.storage


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0002_auto_20251016_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningpackage',
            name='package_file',
            field=models.FileField(help_text='The e-learning package ZIP file', storage=scorm.storage.SCORMLocalStorage(), upload_to=scorm.models.elearning_package_path),
        ),
    ]
