# Generated by Django 3.2.25 on 2025-10-16 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0003_alter_elearningpackage_package_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningtracking',
            name='comments_from_learner',
            field=models.JSONField(default=list, help_text='Comments from learner'),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='comments_from_lms',
            field=models.JSONField(default=list, help_text='Comments from LMS'),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='completion_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='credit',
            field=models.CharField(choices=[('credit', 'Credit'), ('no-credit', 'No Credit')], default='credit', max_length=20),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='entry',
            field=models.CharField(choices=[('ab-initio', 'Ab Initio'), ('resume', 'Resume')], default='ab-initio', max_length=20),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='exit_value',
            field=models.CharField(blank=True, choices=[('time-out', 'Time Out'), ('suspend', 'Suspend'), ('logout', 'Logout'), ('normal', 'Normal'), ('ab-initio', 'Ab Initio')], max_length=20),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='interactions',
            field=models.JSONField(default=dict, help_text='SCORM interactions data'),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='launch_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='learner_preference_audio_captioning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='learner_preference_audio_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='learner_preference_delivery_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='learner_preference_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='mode',
            field=models.CharField(choices=[('browse', 'Browse'), ('normal', 'Normal'), ('review', 'Review')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='objectives',
            field=models.JSONField(default=dict, help_text='SCORM objectives data'),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='registration_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='student_data_mastery_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='student_data_max_time_allowed',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='student_data_time_limit_action',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='suspend_data',
            field=models.TextField(blank=True),
        ),
    ]
