# Generated by Django 3.2.25 on 2025-10-20 15:44

from django.db import migrations, models
import django.db.models.deletion
import scorm.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0002_alter_statement_object_type'),
        ('scorm', '0006_alter_elearningpackage_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningpackage',
            name='lrs',
            field=models.ForeignKey(blank=True, help_text='Associated LRS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lrs.lrs'),
        ),
        migrations.AddField(
            model_name='elearningpackage',
            name='xapi_password',
            field=models.CharField(blank=True, help_text='xAPI authentication password', max_length=255),
        ),
        migrations.AddField(
            model_name='elearningpackage',
            name='xapi_username',
            field=models.CharField(blank=True, help_text='xAPI authentication username', max_length=255),
        ),
        migrations.AddField(
            model_name='elearningpackage',
            name='xapi_version',
            field=models.CharField(default='1.0.3', help_text='xAPI version', max_length=10),
        ),
        migrations.AlterField(
            model_name='elearningpackage',
            name='xapi_actor',
            field=models.JSONField(blank=True, default=dict, help_text='xAPI actor information', validators=[scorm.models.validate_xapi_actor_json]),
        ),
        migrations.AlterField(
            model_name='elearningpackage',
            name='xapi_endpoint',
            field=models.URLField(blank=True, help_text='xAPI endpoint URL', validators=[scorm.models.validate_xapi_endpoint]),
        ),
    ]
