# Generated by Django 3.2.25 on 2025-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0007_auto_20251020_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningpackage',
            name='xapi_password',
            field=models.CharField(blank=True, help_text='xAPI authentication password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elearningpackage',
            name='xapi_username',
            field=models.CharField(blank=True, help_text='xAPI authentication username', max_length=255, null=True),
        ),
    ]
