# Generated by Django 3.2.25 on 2025-10-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0008_add_package_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormpackage',
            name='commit_frequency',
            field=models.IntegerField(default=5000, help_text='Auto-commit frequency in milliseconds (SCORM Cloud default: 10000ms, Ours: 5000ms for better data safety)'),
        ),
    ]
