# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0010_alter_scormpackage_version'),
    ]

    operations = [
        # Add composite indexes for better query performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_attempt_user_package ON scorm_attempt (user_id, scorm_package_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_attempt_user_package;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_attempt_status ON scorm_attempt (lesson_status, completion_status);",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_attempt_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_attempt_scores ON scorm_attempt (score_raw, score_max) WHERE score_raw IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_attempt_scores;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_attempt_timestamps ON scorm_attempt (started_at, last_accessed, completed_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_attempt_timestamps;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_package_topic ON scorm_package (topic_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_package_topic;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_interaction_attempt ON scorm_interaction (attempt_id, interaction_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_interaction_attempt;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_scorm_objective_attempt ON scorm_objective (attempt_id, objective_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_scorm_objective_attempt;"
        ),
    ]
