# Generated by Django 3.2.25 on 2025-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0011_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorminteraction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scorminteraction',
            name='attempt',
        ),
        migrations.AlterUniqueTogether(
            name='scormobjective',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scormobjective',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='completed_slides',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='detailed_tracking',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='last_visited_slide',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='navigation_history',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='score_scaled',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='session_data',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='session_end_time',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='session_start_time',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='time_spent_seconds',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='total_slides',
        ),
        migrations.RemoveField(
            model_name='scormpackage',
            name='commit_frequency',
        ),
        migrations.RemoveField(
            model_name='scormpackage',
            name='package_metadata',
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='cmi_data',
            field=models.JSONField(blank=True, default=dict, help_text='SCORM CMI data model storage'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='total_time',
            field=models.CharField(default='0000:00:00.00', help_text='Total time in SCORM format', max_length=50),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='mastery_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mastery score from manifest', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='version',
            field=models.CharField(choices=[('1.1', 'SCORM 1.1'), ('1.2', 'SCORM 1.2'), ('2004', 'SCORM 2004'), ('xapi', 'xAPI/Tin Can'), ('dual', 'SCORM + xAPI Dual'), ('legacy', 'Legacy SCORM'), ('html5', 'HTML5 Package'), ('storyline', 'Articulate Storyline'), ('captivate', 'Adobe Captivate'), ('lectora', 'Lectora'), ('unknown', 'Unknown Format')], default='1.2', max_length=10),
        ),
        migrations.DeleteModel(
            name='ScormComment',
        ),
        migrations.DeleteModel(
            name='ScormInteraction',
        ),
        migrations.DeleteModel(
            name='ScormObjective',
        ),
    ]
