# Generated by Django 3.2.25 on 2025-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0012_auto_20251014_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormattempt',
            name='completed_slides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='detailed_tracking',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='last_visited_slide',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='navigation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='progress_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='score_scaled',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scaled score (0-1 range)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='time_spent_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='total_slides',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
