# Generated by Django 3.2.25 on 2025-10-17 18:18

import assignments.models
import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0036_update_feedback_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Supporting documents for the assignment (Use AssignmentAttachment for new documents)', null=True, storage=core.s3_storage.MediaS3Storage(), upload_to=assignments.models.assignment_file_path),
        ),
    ]
