# Generated by Django 3.2.25 on 2025-10-16 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('s3', 'S3 Storage'), ('local', 'Local Storage')], max_length=10)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('audio_count', models.PositiveIntegerField(default=0)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('archive_count', models.PositiveIntegerField(default=0)),
                ('other_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('storage_type',)},
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_type', models.CharField(choices=[('s3', 'S3 Storage'), ('local', 'Local Storage')], max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['storage_type'], name='media_libra_storage_08e183_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type'], name='media_libra_file_ty_1c9d81_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='media_libra_uploade_430a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_at'], name='media_libra_uploade_596bd0_idx'),
        ),
    ]
