# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Branch business logo', null=True, upload_to='branch_portals/logos/')),
                ('business_name', models.CharField(help_text='Business name to display on the landing page', max_length=255)),
                ('address_line1', models.CharField(blank=True, help_text='Address line 1', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/Zip code', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary color (Hex code)', max_length=20)),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Secondary color (Hex code)', max_length=20)),
                ('font_family', models.CharField(default='Inter, sans-serif', help_text='Font family', max_length=100)),
                ('welcome_message', models.TextField(blank=True, help_text='Welcome message displayed at the top of the landing page', null=True)),
                ('about_text', models.TextField(blank=True, help_text='About section text', null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the landing page', null=True, upload_to='branch_portals/banners/')),
                ('banner_text', models.CharField(blank=True, help_text='Text to display over the banner image', max_length=255, null=True)),
                ('slug', models.SlugField(help_text='URL slug for the landing page', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this portal is active')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Portal',
                'verbose_name_plural': 'Branch Portals',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount for this item', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Link title/text', max_length=100)),
                ('url', models.URLField(help_text='Link URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Menu Link',
                'verbose_name_plural': 'Custom Menu Links',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureGridItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Feature title', max_length=255)),
                ('description', models.TextField(help_text='Feature description')),
                ('image', models.ImageField(blank=True, help_text='Feature image', null=True, upload_to='branch_portals/feature_grid/')),
                ('link_url', models.URLField(blank=True, help_text='Custom link URL', null=True)),
                ('link_text', models.CharField(default='Learn More', help_text='Custom link button text', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the grid')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Grid Item',
                'verbose_name_plural': 'Feature Grid Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureGridSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, help_text='Optional section title', max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, help_text='Optional section description', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Grid Section',
                'verbose_name_plural': 'Feature Grid Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=255)),
                ('description', models.TextField(help_text='Section description/content')),
                ('image', models.ImageField(blank=True, help_text='Section image', null=True, upload_to='branch_portals/main_content/')),
                ('video', models.FileField(blank=True, help_text='Section video (mp4, avi, mov, wmv)', null=True, upload_to='branch_portals/main_content_videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Main Content Section',
                'verbose_name_plural': 'Main Content Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('waived', 'Payment Waived')], default='pending', help_text='Payment status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Order subtotal before discounts', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Order total', max_digits=10)),
                ('coupon_code', models.CharField(blank=True, help_text='Coupon code used', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this order', null=True)),
                ('user_notes', models.TextField(blank=True, help_text='Notes from the user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was received', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was completed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount for this item', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity (usually 1 for courses)')),
            ],
        ),
        migrations.CreateModel(
            name='PreFooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Short description to display with logo', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether pre-footer is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal', models.OneToOneField(help_text='The portal this pre-footer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pre_footer', to='branch_portal.branchportal')),
            ],
            options={
                'verbose_name': 'Pre-Footer Section',
                'verbose_name_plural': 'Pre-Footer Sections',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='Platform name (e.g., Facebook, Twitter, Instagram)', max_length=50)),
                ('icon', models.ImageField(blank=True, help_text='Custom social media icon (SVG, PNG preferred)', null=True, upload_to='branch_portals/social_icons/')),
                ('url', models.URLField(help_text='Social media profile URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this icon is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_footer', models.ForeignKey(help_text='The pre-footer this icon belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='social_icons', to='branch_portal.prefootersection')),
            ],
            options={
                'verbose_name': 'Social Media Icon',
                'verbose_name_plural': 'Social Media Icons',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
