# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '__first__'),
        ('branch_portal', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(help_text='Course being ordered', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='courses.course'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branch_portal.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(help_text='Branch associated with this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='branches.branch'),
        ),
    ]
