# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0001_initial"),
        ("branch_portal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                help_text="User who placed the order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maincontentsection",
            name="portal",
            field=models.ForeignKey(
                help_text="The portal this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_content_sections",
                to="branch_portal.branchportal",
            ),
        ),
        migrations.AddField(
            model_name="featuregridsection",
            name="portal",
            field=models.ForeignKey(
                help_text="The portal this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_grid_sections",
                to="branch_portal.branchportal",
            ),
        ),
        migrations.AddField(
            model_name="featuregriditem",
            name="feature_section",
            field=models.ForeignKey(
                help_text="The feature section this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="branch_portal.featuregridsection",
            ),
        ),
        migrations.AddField(
            model_name="custommenulink",
            name="pre_footer",
            field=models.ForeignKey(
                help_text="The pre-footer this link belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_links",
                to="branch_portal.prefootersection",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                help_text="Cart this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="branch_portal.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="course",
            field=models.ForeignKey(
                help_text="Course in the cart",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                help_text="User who owns this cart",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branchportal",
            name="branch",
            field=models.OneToOneField(
                help_text="The branch this portal belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal",
                to="branches.branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "course")},
        ),
    ]
