# Generated by Django 4.2.24 on 2025-09-25 16:45

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload file for Video, Audio, Document, or SCORM content', max_length=255, null=True, upload_to=courses.models.content_file_path),
        ),
    ]
