# Generated by Django 3.2.25 on 2025-10-04 11:47

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20251001_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload file for Video, Audio, Document content', max_length=255, null=True, upload_to=courses.models.content_file_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='text', max_length=20),
        ),
    ]
