# Generated by Django 3.2.25 on 2025-10-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0001_initial'),
        ('courses', '0005_auto_20251004_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Survey to be completed by learners after finishing this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course_reviews.survey'),
        ),
    ]
