# Generated by Django 3.2.25 on 2025-10-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_scorm_references'),
    ]

    operations = [
        # Remove all SCORM-related tables
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_cloud_scormdestination CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_cloud_scormdispatch CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_cloud_scormpackage CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_cloud_scormregistration CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_cloud_scormcloudcontent CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS account_settings_scormintegration CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS native_scorm_nativescormpackage CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS native_scorm_nativescormprogress CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS native_scorm_nativescormsession CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_package CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_comment CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_objective CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_interaction CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_attempt CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_event CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_scormobjective CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_scorminteraction CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scorm_scormevent CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
