# Generated by Django 3.2.25 on 2025-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_all_scorm_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicprogress',
            options={'ordering': ['-last_accessed']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Text', 'Text'), ('Audio', 'Audio'), ('Web', 'Web Content'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('SCORM', 'SCORM Package'), ('EmbedVideo', 'Embedded Video'), ('Conference', 'ILT/Conference'), ('Discussion', 'Discussion')], max_length=20),
        ),
    ]
