# Generated by Django 3.2.25 on 2025-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20251016_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable_mastery_auto_complete',
            field=models.BooleanField(default=True, help_text='Enable automatic completion based on mastery score achievement'),
        ),
        migrations.AddField(
            model_name='course',
            name='scorm_mastery_score',
            field=models.FloatField(default=70.0, help_text='Default mastery score percentage for SCORM content (0-100)'),
        ),
    ]
