# Generated by Django 3.2.25 on 2025-10-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_add_prerequisites_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='enrollment_source',
            field=models.CharField(choices=[('manual', 'Manual Enrollment'), ('auto_prerequisite', 'Auto-enrolled for Prerequisites'), ('auto_dependent', 'Auto-enrolled from Dependent Course'), ('bulk', 'Bulk Enrollment'), ('self', 'Self Enrollment')], default='manual', help_text='How the user was enrolled in this course', max_length=20),
        ),
    ]
