# Generated by Django 3.2.25 on 2025-10-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branchuserlimits_total_limit'),
        ('courses', '0015_alter_courseenrollment_enrollment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this course belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_courses', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, help_text='The learners enrolled in this course.', related_name='user_enrolled_courses', through='courses.CourseEnrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(help_text='The instructor assigned to this course.', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_instructor_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
