# Generated by Django 3.2.25 on 2025-10-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20251018_0812'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS courses_course_prerequisites (
                id SERIAL PRIMARY KEY,
                from_course_id INTEGER NOT NULL REFERENCES courses_course(id) ON DELETE CASCADE,
                to_course_id INTEGER NOT NULL REFERENCES courses_course(id) ON DELETE CASCADE,
                UNIQUE(from_course_id, to_course_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS courses_course_prerequisites;"
        ),
    ]
