# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_email_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the user accepted Terms of Service and Privacy Policy', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Email address - must be unique across all users', max_length=254, unique=True),
        ),
    ]
