# Generated by Django 3.2.25 on 2025-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251022_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visual_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, help_text='Visual learning style score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kinesthetic_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, help_text='Kinesthetic learning style score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='auditory_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, help_text='Auditory learning style score'),
        ),
    ]