# Generated by Django 3.2.25 on 2025-10-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchuserlimits_total_limit'),
        ('users', '0003_auto_20251022_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Street address/house number', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Apartment/Suite/Unit/Building', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='assigned_instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to this learner.', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user belongs to. Not required for Global Admin users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_name',
            field=models.CharField(blank=True, help_text='Family name/surname', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='given_names',
            field=models.CharField(blank=True, help_text='Given name(s)/first name(s)', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_role',
            field=models.CharField(blank=True, help_text='Current or most recent job role', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='manualassessmententry',
            name='subject',
            field=models.CharField(help_text='Subject or assessment name', max_length=800),
        ),
        migrations.AlterField(
            model_name='userquizassignment',
            name='item_name',
            field=models.CharField(help_text='Display name for the quiz assignment (defaults to quiz title)', max_length=800),
        ),
    ]
