# Generated by Django 3.2.25 on 2025-10-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_increase_char_limits_to_800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auditory_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='kinesthetic_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='visual_score',
        ),
    ]
