# Generated by Django 3.2.25 on 2025-10-29 09:47

import core.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', core.utils.fields.TinyMCEField(blank=True, default='')),
                ('short_message', models.CharField(max_length=500)),
                ('recipient_type', models.CharField(choices=[('all_users', 'All Users'), ('role', 'By Role'), ('branch', 'By Branch'), ('group', 'By Group'), ('course', 'By Course'), ('custom', 'Custom List')], max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', core.utils.fields.TinyMCEField(blank=True, default='')),
                ('short_message', models.CharField(help_text='Brief version for previews and mobile notifications', max_length=500)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to redirect when notification is clicked')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification should expire', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('read', 'Read'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('deleted', 'Deleted'), ('bulk_sent', 'Bulk Sent')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('web_notifications_enabled', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=False)),
                ('weekly_digest_enabled', models.BooleanField(default=True)),
                ('certificate_expiry_reminder_days', models.IntegerField(default=30, help_text='How many days before certificate expiry to send reminder (0 = no reminder)')),
                ('certificate_expiry_reminder_intervals', models.JSONField(blank=True, default=list, help_text='List of days before expiry to send reminders (e.g., [30, 7, 1])')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', core.utils.fields.TinyMCEField(blank=True, default='')),
                ('short_message_template', models.CharField(max_length=500)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('default_action_url', models.URLField(blank=True)),
                ('default_action_text', models.CharField(blank=True, max_length=100)),
                ('available_variables', models.JSONField(default=list, help_text='List of available variables for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_be_disabled', models.BooleanField(default=True, help_text='Whether users can disable this notification type')),
                ('available_to_roles', models.JSONField(default=list, help_text='List of roles that can receive this notification type (empty = all roles)')),
                ('default_email_enabled', models.BooleanField(default=True)),
                ('default_web_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTypeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('web_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='lms_notifications.notificationtype')),
            ],
        ),
    ]
