# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lms_notifications", "0001_initial"),
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0002_initial"),
        ("assignments", "0003_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtypesettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_type_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtype",
            index=models.Index(
                fields=["name", "is_active"], name="lms_notific_name_db0332_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_notification_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_notifications.notificationtype",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="bulk_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="lms_notifications.bulknotification",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="lms_notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="lms_notifications.notificationtype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="assignments.assignment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulknotification",
            name="custom_recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_bulk_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulknotification",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_notifications.notificationtype",
            ),
        ),
        migrations.AddField(
            model_name="bulknotification",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_notifications_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulknotification",
            name="target_branches",
            field=models.ManyToManyField(blank=True, to="branches.branch"),
        ),
        migrations.AddField(
            model_name="bulknotification",
            name="target_courses",
            field=models.ManyToManyField(blank=True, to="courses.course"),
        ),
        migrations.AddField(
            model_name="bulknotification",
            name="target_groups",
            field=models.ManyToManyField(blank=True, to="groups.branchgroup"),
        ),
        migrations.AddIndex(
            model_name="notificationtypesettings",
            index=models.Index(
                fields=["user", "notification_type"],
                name="lms_notific_user_id_4992e0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationtypesettings",
            unique_together={("user", "notification_type")},
        ),
        migrations.AddIndex(
            model_name="notificationsettings",
            index=models.Index(fields=["user"], name="lms_notific_user_id_7ddb75_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["notification", "-timestamp"],
                name="lms_notific_notific_339f94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="lms_notific_user_id_ed519e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="lms_notific_action_d78cf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="lms_notific_recipie_8bca96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="lms_notific_recipie_15c3f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "-created_at"],
                name="lms_notific_notific_70822b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="lms_notific_priorit_9dcfb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["email_sent", "-created_at"],
                name="lms_notific_email_s_431bdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bulknotification",
            index=models.Index(
                fields=["sender", "-created_at"], name="lms_notific_sender__ae6ca6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulknotification",
            index=models.Index(
                fields=["status", "-created_at"], name="lms_notific_status_aef343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulknotification",
            index=models.Index(
                fields=["scheduled_for"], name="lms_notific_schedul_42835e_idx"
            ),
        ),
    ]
