# Generated by Django 3.2.25 on 2025-11-22 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this notification type is enabled for users in this branch')),
                ('default_email_enabled', models.BooleanField(default=True, help_text='Default email setting for new users in this branch')),
                ('default_web_enabled', models.BooleanField(default=True, help_text='Default web setting for new users in this branch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='branches.branch')),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_branch_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='lms_notifications.notificationtype')),
            ],
            options={
                'verbose_name': 'Branch Notification Setting',
                'verbose_name_plural': 'Branch Notification Settings',
            },
        ),
        migrations.AddIndex(
            model_name='branchnotificationsettings',
            index=models.Index(fields=['branch', 'notification_type'], name='lms_notific_branch__06d53f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchnotificationsettings',
            index=models.Index(fields=['branch', 'is_enabled'], name='lms_notific_branch__bacd08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchnotificationsettings',
            unique_together={('branch', 'notification_type')},
        ),
    ]
