# Generated by Django 3.2.25 on 2025-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_notifications', '0003_add_todo_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='certificate_expiry_reminder_days',
            field=models.IntegerField(default=30, help_text='How many days before certificate expiry to send reminder (0 = no reminder)'),
        ),
    ]
