# Generated by Django 3.2.25 on 2025-10-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_notifications', '0005_add_certificate_expiry_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='certificate_expiry_reminder_intervals',
            field=models.JSONField(blank=True, default=list, help_text='List of days before expiry to send reminders (e.g., [30, 7, 1])'),
        ),
    ]
