# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_rubrics', '0001_initial'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencerubricevaluation',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_evaluations', to='lms_rubrics.rubriccriterion'),
        ),
    ]
