# Generated by Django 3.2.25 on 2025-10-17 18:18

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencefile',
            name='local_file',
            field=models.FileField(blank=True, null=True, storage=core.s3_storage.MediaS3Storage(), upload_to='conference_files/%Y/%m/%d/'),
        ),
    ]
