# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_conference_time_slots'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conference',
            name='conferences_use_tim_idx',
        ),
        migrations.RemoveIndex(
            model_name='conferencetimeslot',
            name='conferences_ts_conf_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='conferencetimeslot',
            name='conferences_ts_avail_idx',
        ),
        migrations.RemoveIndex(
            model_name='conferencetimeslotselection',
            name='conferences_tss_slot_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='conferencetimeslotselection',
            name='conferences_tss_conf_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='conferencetimeslotselection',
            name='conferences_tss_selected_idx',
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['use_time_slots'], name='conferences_use_tim_87767d_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencetimeslot',
            index=models.Index(fields=['conference', 'date', 'start_time'], name='conferences_confere_bf38fd_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencetimeslot',
            index=models.Index(fields=['is_available'], name='conferences_is_avai_b8bf33_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencetimeslotselection',
            index=models.Index(fields=['time_slot', 'user'], name='conferences_time_sl_849e56_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencetimeslotselection',
            index=models.Index(fields=['conference', 'user'], name='conferences_confere_f00ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencetimeslotselection',
            index=models.Index(fields=['selected_at'], name='conferences_selecte_fc5755_idx'),
        ),
    ]
