# Generated by Django 3.2.25 on 2025-11-20 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferences', '0006_conferencerecording_onedrive_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conferencerecording',
            name='conferences_onedrive_item_idx',
        ),
        migrations.RemoveIndex(
            model_name='conferencerecording',
            name='conferences_onedrive_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='conferencetimeslotselection',
            unique_together={('time_slot', 'user')},
        ),
    ]
