# Generated by Django 3.2.25 on 2025-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20251120_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='online_meeting_id',
            field=models.CharField(blank=True, help_text='Teams online meeting ID (required for recording)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conferencetimeslot',
            name='online_meeting_id',
            field=models.CharField(blank=True, help_text='Teams online meeting ID (required for recording)', max_length=255, null=True),
        ),
    ]
