# Generated by Django 3.2.25 on 2025-11-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_add_online_meeting_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conferencetimeslot',
            unique_together={('conference', 'date', 'start_time', 'end_time')},
        ),
    ]
