# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '__first__'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storagequotawarning',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='User whose upload triggered this warning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_storage_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filestorageusage',
            name='user',
            field=models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='file_storage_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchstoragelimit',
            name='branch',
            field=models.OneToOneField(help_text='The branch these storage limits apply to', on_delete=django.db.models.deletion.CASCADE, related_name='storage_limits', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='branchstoragelimit',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Global admin who last updated these limits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_storage_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storagequotawarning',
            index=models.Index(fields=['branch', 'created_at'], name='core_storag_branch__4d6fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='storagequotawarning',
            index=models.Index(fields=['warning_type', 'created_at'], name='core_storag_warning_b93040_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorageusage',
            index=models.Index(fields=['user', 'created_at'], name='core_filest_user_id_a12971_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorageusage',
            index=models.Index(fields=['user', 'is_deleted'], name='core_filest_user_id_72069b_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorageusage',
            index=models.Index(fields=['source_app', 'created_at'], name='core_filest_source__d9ee1c_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorageusage',
            index=models.Index(fields=['created_at'], name='core_filest_created_fb174f_idx'),
        ),
    ]
