# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntraGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_group_id', models.CharField(max_length=255)),
                ('entra_group_name', models.CharField(max_length=255)),
                ('entra_group_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('target_group_type', models.CharField(choices=[('user', 'User Group'), ('course', 'Course Group')], default='user', help_text='Type of LMS group this Entra ID group should map to', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_frequency_minutes', models.PositiveIntegerField(default=60)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never Synced'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='never', max_length=20)),
                ('total_users_synced', models.PositiveIntegerField(default=0)),
                ('last_sync_users_count', models.PositiveIntegerField(default=0)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsMeetingSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_meeting_id', models.CharField(max_length=255, unique=True)),
                ('teams_meeting_url', models.URLField(blank=True, max_length=500, null=True)),
                ('attendance_synced', models.BooleanField(default=False)),
                ('recordings_synced', models.BooleanField(default=False)),
                ('chat_synced', models.BooleanField(default=False)),
                ('files_synced', models.BooleanField(default=False)),
                ('last_attendance_sync', models.DateTimeField(blank=True, null=True)),
                ('last_recording_sync', models.DateTimeField(blank=True, null=True)),
                ('last_chat_sync', models.DateTimeField(blank=True, null=True)),
                ('last_file_sync', models.DateTimeField(blank=True, null=True)),
                ('meeting_duration_minutes', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('meeting_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('sync_errors', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('entra_groups', 'Entra ID Groups Sync'), ('entra_users', 'Entra ID Users Sync'), ('meeting_attendance', 'Meeting Attendance Sync'), ('meeting_recordings', 'Meeting Recordings Sync'), ('meeting_chat', 'Meeting Chat Sync'), ('meeting_files', 'Meeting Files Sync'), ('full_sync', 'Full Teams Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('sync_direction', models.CharField(choices=[('to_teams', 'To Teams'), ('from_teams', 'From Teams'), ('bidirectional', 'Bidirectional')], default='from_teams', max_length=20)),
                ('sync_metadata', models.JSONField(blank=True, default=dict)),
                ('api_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamsUserSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entra_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('entra_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('sync_metadata', models.JSONField(blank=True, default=dict)),
                ('entra_groups', models.JSONField(blank=True, default=list)),
                ('lms_groups', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
