# Generated by Django 3.2.25 on 2025-10-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_increase_char_limits_to_800'),
        ('teams_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entragroupmapping',
            name='target_course',
            field=models.ForeignKey(blank=True, help_text='Specific course to map to (if course group type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entra_group_mappings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='entragroupmapping',
            name='target_group_type',
            field=models.CharField(choices=[('user', 'User Group'), ('course', 'Course Group')], default='user', help_text='Type of LMS group this Entra ID group should map to', max_length=10),
        ),
    ]
