# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('account_settings', '0001_initial'),
        ('teams_integration', '0001_initial'),
        ('groups', '0001_initial'),
        ('conferences', '0002_conferencerubricevaluation_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsusersync',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_syncs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamssynclog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_sync_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamssynclog',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='account_settings.teamsintegration'),
        ),
        migrations.AddField(
            model_name='teamsmeetingsync',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_syncs', to='conferences.conference'),
        ),
        migrations.AddField(
            model_name='entragroupmapping',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entra_mappings', to='account_settings.teamsintegration'),
        ),
        migrations.AddField(
            model_name='entragroupmapping',
            name='lms_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entra_mappings', to='groups.branchgroup'),
        ),
        migrations.AddField(
            model_name='entragroupmapping',
            name='target_course',
            field=models.ForeignKey(blank=True, help_text='Specific course to map to (if course group type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entra_group_mappings', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='teamsusersync',
            index=models.Index(fields=['user'], name='teams_integ_user_id_60b6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='teamsusersync',
            index=models.Index(fields=['entra_user_id'], name='teams_integ_entra_u_7adce0_idx'),
        ),
        migrations.AddIndex(
            model_name='teamsusersync',
            index=models.Index(fields=['sync_status'], name='teams_integ_sync_st_a69510_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamsusersync',
            unique_together={('user', 'entra_user_id')},
        ),
        migrations.AddIndex(
            model_name='teamssynclog',
            index=models.Index(fields=['integration', 'sync_type'], name='teams_integ_integra_15d46e_idx'),
        ),
        migrations.AddIndex(
            model_name='teamssynclog',
            index=models.Index(fields=['status', 'started_at'], name='teams_integ_status_f4b001_idx'),
        ),
        migrations.AddIndex(
            model_name='teamssynclog',
            index=models.Index(fields=['started_at'], name='teams_integ_started_bddfe8_idx'),
        ),
        migrations.AddIndex(
            model_name='teamsmeetingsync',
            index=models.Index(fields=['conference'], name='teams_integ_confere_99a98d_idx'),
        ),
        migrations.AddIndex(
            model_name='teamsmeetingsync',
            index=models.Index(fields=['teams_meeting_id'], name='teams_integ_teams_m_d1fd91_idx'),
        ),
        migrations.AddIndex(
            model_name='teamsmeetingsync',
            index=models.Index(fields=['meeting_status'], name='teams_integ_meeting_28d3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='entragroupmapping',
            index=models.Index(fields=['integration', 'is_active'], name='teams_integ_integra_b7027a_idx'),
        ),
        migrations.AddIndex(
            model_name='entragroupmapping',
            index=models.Index(fields=['lms_group'], name='teams_integ_lms_gro_b67e23_idx'),
        ),
        migrations.AddIndex(
            model_name='entragroupmapping',
            index=models.Index(fields=['last_sync_at'], name='teams_integ_last_sy_5d8a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entragroupmapping',
            unique_together={('integration', 'entra_group_id')},
        ),
    ]
