# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharePointConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("field_mismatch", "Field Value Mismatch"),
                            ("timestamp_conflict", "Timestamp Conflict"),
                            ("missing_record", "Missing Record"),
                            ("duplicate_record", "Duplicate Record"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_type", models.CharField(max_length=50)),
                ("record_id", models.CharField(max_length=100)),
                (
                    "sharepoint_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                ("lms_value", models.JSONField(blank=True, null=True)),
                ("sharepoint_value", models.JSONField(blank=True, null=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("pending_review", "Pending Manual Review"),
                            ("auto_resolved", "Auto Resolved"),
                            ("manually_resolved", "Manually Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="detected",
                        max_length=30,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SharePoint Conflict",
                "verbose_name_plural": "SharePoint Conflicts",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="SharePointSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("sync_to_sharepoint", "Sync to SharePoint"),
                            ("sync_from_sharepoint", "Sync from SharePoint"),
                            ("bidirectional_sync", "Bidirectional Sync"),
                            ("conflict_resolution", "Conflict Resolution"),
                            ("monitoring", "Change Monitoring"),
                            ("health_check", "Health Check"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("model_type", models.CharField(blank=True, max_length=50, null=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("result_summary", models.JSONField(default=dict)),
                ("error_details", models.JSONField(default=list)),
                ("task_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "SharePoint Sync Log",
                "verbose_name_plural": "SharePoint Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
