# Generated by Django 3.2.25 on 2025-10-22 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_settings', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
