# Generated by Django 3.2.25 on 2025-11-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0003_auto_20251111_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsintegration',
            name='service_account_email',
            field=models.EmailField(blank=True, help_text='Service account email (must exist in Azure AD with Exchange Online license) used for creating Teams meetings when user email is not available or invalid', max_length=254, null=True),
        ),
    ]
