# Generated by Django 3.2.25 on 2025-10-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0004_auto_20251001_1548'),
        ('branches', '0001_initial'),
        ('users', '0002_auto_20251022_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormintegration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='name',
            field=models.CharField(default='SCORM Integration', max_length=255),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for SCORM API', null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='pens_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='test_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='last_test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='request_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='upload_timeout',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='max_upload_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scorm_integrations',
                to='branches.branch'
            ),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scorm_integrations',
                to='users.customuser'
            ),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
