# Generated by Django 3.2.25 on 2025-10-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0005_auto_20251022_0742'),
        ('account_settings', '0006_auto_20251022_0752'),
    ]

    operations = [
    ]
