# Generated by Django 3.2.25 on 2025-10-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchuserlimits_total_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_settings', '0007_merge_0005_auto_20251022_0742_0006_auto_20251022_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scormintegration',
            options={},
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='app_id',
            field=models.CharField(blank=True, help_text='SCORM Cloud Application ID', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='base_url',
            field=models.URLField(default='https://cloud.scorm.com/api/v2', help_text='SCORM Cloud API Base URL'),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this SCORM integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='is_tested',
            field=models.BooleanField(default=False, help_text='Whether SCORM Cloud configuration has been tested successfully'),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='last_test_date',
            field=models.DateTimeField(blank=True, help_text='Date when SCORM Cloud configuration was last tested', null=True),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='max_upload_size',
            field=models.PositiveIntegerField(default=629145600, help_text='Maximum upload size in bytes (600MB default)'),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='name',
            field=models.CharField(help_text='Name for this integration configuration', max_length=255),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='pens_key',
            field=models.CharField(blank=True, help_text='SCORM Cloud PENS (Package Exchange Notification Services) Key for notifications', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='request_timeout',
            field=models.PositiveIntegerField(default=900, help_text='Request timeout in seconds (15 minutes default)'),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='secret_key',
            field=models.CharField(blank=True, help_text='SCORM Cloud Secret Key', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='test_error',
            field=models.TextField(blank=True, help_text='Last SCORM Cloud test error message if any', null=True),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='upload_timeout',
            field=models.PositiveIntegerField(default=1800, help_text='Upload timeout in seconds (30 minutes default)'),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scormintegration',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Verify SSL certificates for SCORM Cloud API'),
        ),
    ]
