# Generated by Django 3.2.25 on 2025-10-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0008_increase_char_limits_to_800'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaladminsettings',
            name='teams_integration_enabled',
            field=models.BooleanField(default=False, help_text='Enable Microsoft Teams integration system-wide'),
        ),
        migrations.AddField(
            model_name='globaladminsettings',
            name='teams_sync_attendance',
            field=models.BooleanField(default=True, help_text='Enable Teams meeting attendance tracking'),
        ),
        migrations.AddField(
            model_name='globaladminsettings',
            name='teams_sync_entra_groups',
            field=models.BooleanField(default=True, help_text='Enable Entra ID group synchronization with Teams'),
        ),
        migrations.AddField(
            model_name='globaladminsettings',
            name='teams_sync_meetings',
            field=models.BooleanField(default=True, help_text='Enable Teams meeting synchronization'),
        ),
    ]
