# Generated by Django 3.2.25 on 2025-10-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0009_auto_20251024_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormintegration',
            name='scorm_endpoint',
            field=models.URLField(blank=True, help_text='Legacy SCORM endpoint field', null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='scorm_password',
            field=models.CharField(blank=True, help_text='Legacy SCORM password field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='scorm_username',
            field=models.CharField(blank=True, help_text='Legacy SCORM username field', max_length=255, null=True),
        ),
    ]
