# Generated by Django 3.2.25 on 2025-10-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0010_add_scorm_legacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormintegration',
            name='scorm_endpoint',
        ),
        migrations.RemoveField(
            model_name='scormintegration',
            name='scorm_password',
        ),
        migrations.RemoveField(
            model_name='scormintegration',
            name='scorm_username',
        ),
    ]
