# Generated by Django 4.2.19 on 2025-05-14 10:27

from django.db import migrations, models
import lms_rubrics.models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_rubrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubriccriterion",
            name="description",
            field=models.TextField(
                validators=[lms_rubrics.models.validate_description]
            ),
        ),
        migrations.AlterField(
            model_name="rubricrating",
            name="description",
            field=models.TextField(
                validators=[lms_rubrics.models.validate_description]
            ),
        ),
    ]
