# Generated by Django 4.2.19 on 2025-07-13 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assignments", "0001_initial"),
        ("quiz", "0001_initial"),
        ("conferences", "0001_initial"),
        ("discussions", "0001_initial"),
        ("lms_rubrics", "0016_rubricoverallfeedback"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rubricoverallfeedback",
            unique_together={
                ("discussion", "student"),
                ("conference", "student"),
                ("submission", "student"),
            },
        ),
        migrations.AddField(
            model_name="rubricoverallfeedback",
            name="quiz_attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="Related quiz attempt if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_overall_feedback",
                to="quiz.quizattempt",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rubricoverallfeedback",
            unique_together={
                ("discussion", "student"),
                ("conference", "student"),
                ("quiz_attempt", "student"),
                ("submission", "student"),
            },
        ),
        migrations.AddIndex(
            model_name="rubricoverallfeedback",
            index=models.Index(
                fields=["quiz_attempt", "student"],
                name="lms_rubrics_quiz_at_c5c134_idx",
            ),
        ),
    ]
