# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_rubrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrubricevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_rubric_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizrubricevaluation',
            name='quiz_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluations', to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizrubricevaluation',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_evaluations', to='lms_rubrics.rubricrating'),
        ),
        migrations.AddField(
            model_name='quizgradeoverride',
            name='override_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizgradeoverride',
            name='quiz_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='override', to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rubric',
            field=models.ForeignKey(blank=True, help_text='Optional rubric used for additional grading criteria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='lms_rubrics.rubric'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='matchingpair',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question'], name='quiz_useran_attempt_d3207a_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['is_correct'], name='quiz_useran_is_corr_1f1e34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizrubricevaluation',
            unique_together={('quiz_attempt', 'criterion')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user'], name='quiz_quizat_quiz_id_fd8459_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-start_time'], name='quiz_quizat_user_id_bcc702_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['is_completed'], name='quiz_quizat_is_comp_f42b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['creator', '-created_at'], name='quiz_quiz_creator_ea4bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', '-created_at'], name='quiz_quiz_course__04b9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['expires_at'], name='quiz_quiz_expires_02df79_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_f13328_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingpair',
            index=models.Index(fields=['question', 'pair_order'], name='quiz_matchi_questio_1e3f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'answer_order'], name='quiz_answer_questio_a9733d_idx'),
        ),
    ]
