# Generated by Django 3.2.25 on 2025-10-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_question_learning_style'),
    ]

    operations = [
    ]
