# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_rubrics', '0001_initial'),
        ('branches', '__first__'),
        ('courses', '0001_initial'),
        ('lms_outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccriterionoutcome',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_connections', to='lms_rubrics.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='rubriccriterionoutcome',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_connections', to='lms_outcomes.outcome'),
        ),
        migrations.AddField(
            model_name='outcomegroup',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this outcome group belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_groups', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='outcomegroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_groups', to='courses.course'),
        ),
    ]
