# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0002_initial"),
        ("lms_outcomes", "0002_initial"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcomegroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this outcome group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_outcome_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outcomegroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="lms_outcomes.outcomegroup",
            ),
        ),
        migrations.AddField(
            model_name="outcomeevaluation",
            name="outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="lms_outcomes.outcome",
            ),
        ),
        migrations.AddField(
            model_name="outcomeevaluation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcome_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outcomealignment",
            name="outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alignments",
                to="lms_outcomes.outcome",
            ),
        ),
        migrations.AddField(
            model_name="outcome",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The branch this outcome belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="outcome",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="outcome",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this outcome",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_outcomes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outcome",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="lms_outcomes.outcomegroup",
            ),
        ),
        migrations.AddIndex(
            model_name="rubriccriterionoutcome",
            index=models.Index(
                fields=["criterion"], name="lms_outcome_criteri_c415f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rubriccriterionoutcome",
            index=models.Index(
                fields=["outcome"], name="lms_outcome_outcome_8214b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rubriccriterionoutcome",
            unique_together={("criterion", "outcome")},
        ),
        migrations.AddIndex(
            model_name="outcomeevaluation",
            index=models.Index(
                fields=["student", "outcome"], name="lms_outcome_student_604d5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outcomeevaluation",
            index=models.Index(
                fields=["outcome", "-score"], name="lms_outcome_outcome_5e18e0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="outcomeevaluation",
            unique_together={("student", "outcome")},
        ),
        migrations.AddIndex(
            model_name="outcomealignment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="lms_outcome_content_a88a63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outcomealignment",
            index=models.Index(
                fields=["outcome"], name="lms_outcome_outcome_49addc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="outcomealignment",
            unique_together={("outcome", "content_type", "object_id")},
        ),
    ]
