# Generated by Django 3.2.25 on 2025-10-29 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, help_text='Average rating from all rating fields', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review_text', models.TextField(blank=True, help_text='Compiled review text')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Is this review published?')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Survey title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Survey description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this survey active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Field label/question', max_length=800)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('rating', 'Star Rating'), ('number', 'Number'), ('email', 'Email')], default='text', help_text='Type of input field', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Is this field required?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of field')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input', max_length=800)),
                ('help_text', models.TextField(blank=True, help_text='Help text for the field')),
                ('max_rating', models.PositiveIntegerField(default=5, help_text='Maximum rating value (for rating fields)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, help_text='Text response')),
                ('rating_response', models.PositiveIntegerField(blank=True, help_text='Rating response (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
