# Generated by Django 3.2.25 on 2025-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='label',
            field=models.CharField(help_text='Field label/question', max_length=800),
        ),
        migrations.AlterField(
            model_name='surveyfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for input', max_length=800),
        ),
    ]
