# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_reviews', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='course',
            field=models.ForeignKey(help_text='Course this response is related to', on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_field',
            field=models.ForeignKey(help_text='Survey field this response is for', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='course_reviews.surveyfield'),
        ),
    ]
