# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('course_reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(help_text='User who submitted this response', on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyfield',
            name='survey',
            field=models.ForeignKey(help_text='Survey this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='course_reviews.survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this survey belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this survey', on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(help_text='Course being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='survey',
            field=models.ForeignKey(help_text='Survey this review is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reviews', to='course_reviews.survey'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the review', on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['user', 'course'], name='course_revi_user_id_8e0673_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['course', 'submitted_at'], name='course_revi_course__38538d_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey_field'], name='course_revi_survey__5d3730_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('survey_field', 'user', 'course')},
        ),
        migrations.AddIndex(
            model_name='surveyfield',
            index=models.Index(fields=['survey', 'order'], name='course_revi_survey__e78f66_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'branch'], name='course_revi_is_acti_1b03d6_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_by'], name='course_revi_created_b4e760_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', 'is_published'], name='course_revi_course__3e6095_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['user'], name='course_revi_user_id_ea2c01_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['average_rating'], name='course_revi_average_d09e71_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['-submitted_at'], name='course_revi_submitt_2a18a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('course', 'user', 'survey')},
        ),
    ]
