# Generated by Django 3.2.25 on 2025-11-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0005_fix_average_rating_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Is this field required?'),
        ),
    ]
