# Generated by Django 3.2.25 on 2025-11-27 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0006_change_surveyfield_is_required_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfield',
            name='max_rating',
            field=models.PositiveIntegerField(default=5, help_text='Maximum rating value (for rating fields, 1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='rating_response',
            field=models.PositiveIntegerField(blank=True, help_text='Rating response (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
