# Generated by Django 3.2.25 on 2025-10-01 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branchuserlimits_total_limit'),
        ('role_management', '0002_initial'),
        ('account_settings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontrolsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='databackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globaladminsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menucontrolsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menucontrolsettings',
            name='visible_to_custom_roles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'name': 'custom'}, to='role_management.Role'),
        ),
        migrations.AddField(
            model_name='paypalintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this payment integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='paypalintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='branch',
            field=models.OneToOneField(blank=True, help_text='The branch these portal settings belong to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_settings', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this SCORM integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='scormintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharepointintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this SharePoint integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='sharepointintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stripeintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this payment integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stripeintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamsintegration',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this integration belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='teamsintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zoomintegration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menucontrolsettings',
            name='menu_section',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('user_management', 'User Management'), ('branch_portal', 'Branch Portal'), ('courses', 'Courses'), ('assignments', 'Assignments'), ('communication', 'Communication'), ('calendar', 'Calendar'), ('reports', 'Reports'), ('certificates', 'Certificates'), ('role_management', 'Role Management'), ('account_settings', 'Account & Settings'), ('subscription', 'Subscription')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menucontrolsettings',
            name='submenu_item',
            field=models.CharField(blank=True, choices=[('branches', 'Branches'), ('groups', 'Groups'), ('users', 'Users'), ('branch_dashboard', 'Branch Dashboard'), ('order_management', 'Order Management'), ('course_list', 'Course List'), ('categories', 'Categories'), ('outcomes', 'Outcomes'), ('messages', 'Messages'), ('discussions', 'Discussions'), ('conferences', 'Conferences'), ('notifications', 'Notifications'), ('reports_overview', 'Reports Overview'), ('user_reports', 'User Reports'), ('group_reports', 'Group Reports'), ('branch_reports', 'Branch Reports'), ('course_reports', 'Course Reports'), ('learning_activities', 'Learning Activities'), ('training_matrix', 'Training Matrix'), ('gradebook', 'Gradebook'), ('timeline', 'Timeline'), ('custom_reports', 'Custom Reports')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='menucontrolsettings',
            unique_together={('menu_section', 'submenu_item')},
        ),
    ]
