# Generated by Django 3.2.25 on 2025-10-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0004_auto_20251001_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegrationCredential',
        ),
        migrations.RemoveField(
            model_name='portalsettings',
            name='user',
        ),
    ]
