# Generated by Django 4.2.19 on 2025-05-14 18:49

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("lms_rubrics", "0002_alter_rubriccriterion_description_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="rubricrating",
            name="title",
            field=models.CharField(default="Rating", max_length=255),
        )
    ]
