# Generated by Django 4.2.19 on 2025-05-22 14:05

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("lms_rubrics", "0003_alter_rubricevaluation_unique_together"),
        ("lms_rubrics", "0004_add_rubric_evaluation")
    ]

    operations = []
