# Generated by Django 3.2.25 on 2025-10-17 20:41

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop orphaned database tables that have no corresponding models or apps.
    
    This migration removes 10 orphaned tables from the database:
    - 8 gamification tables (lms_gamification_*)
    - 2 media tables (lms_media_*)
    
    These tables were left behind when the corresponding apps were removed
    from the codebase but migrations were never cleaned up.
    
    Tables being dropped:
    1. lms_gamification_badge
    2. lms_gamification_level  
    3. lms_gamification_point
    4. lms_gamification_pointrule
    5. lms_gamification_reward
    6. lms_gamification_rewardredemption
    7. lms_gamification_userbadge
    8. lms_gamification_userlevel
    9. lms_media_file
    10. lms_media_statistics
    """

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        # Drop gamification tables (8 tables)
        migrations.RunSQL(
            sql="""
            -- Drop gamification tables in dependency order
            DROP TABLE IF EXISTS lms_gamification_rewardredemption CASCADE;
            DROP TABLE IF EXISTS lms_gamification_userbadge CASCADE;
            DROP TABLE IF EXISTS lms_gamification_userlevel CASCADE;
            DROP TABLE IF EXISTS lms_gamification_point CASCADE;
            DROP TABLE IF EXISTS lms_gamification_pointrule CASCADE;
            DROP TABLE IF EXISTS lms_gamification_reward CASCADE;
            DROP TABLE IF EXISTS lms_gamification_badge CASCADE;
            DROP TABLE IF EXISTS lms_gamification_level CASCADE;
            """,
            reverse_sql="""
            -- Cannot reverse - tables were orphaned
            -- If needed, these tables would need to be recreated from scratch
            """,
        ),
        
        # Drop media tables (2 tables)
        migrations.RunSQL(
            sql="""
            -- Drop media tables
            DROP TABLE IF EXISTS lms_media_statistics CASCADE;
            DROP TABLE IF EXISTS lms_media_file CASCADE;
            """,
            reverse_sql="""
            -- Cannot reverse - tables were orphaned
            -- If needed, these tables would need to be recreated from scratch
            """,
        ),
    ]
