# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinymce_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchaitokenlimit',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Global admin who last updated these limits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_token_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aitokenusage',
            name='user',
            field=models.ForeignKey(help_text='User who generated AI content', on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aitokenusage',
            index=models.Index(fields=['user', 'created_at'], name='tinymce_edi_user_id_61025d_idx'),
        ),
        migrations.AddIndex(
            model_name='aitokenusage',
            index=models.Index(fields=['created_at'], name='tinymce_edi_created_6ae4fa_idx'),
        ),
    ]
