# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificateElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("name", "Name"),
                            ("grade", "Grade"),
                            ("date", "Date"),
                            ("signature", "Signature"),
                            ("image", "Image"),
                            ("course", "Course Name"),
                        ],
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "position_x",
                    models.FloatField(help_text="X coordinate in percentage (0-100)"),
                ),
                (
                    "position_y",
                    models.FloatField(help_text="Y coordinate in percentage (0-100)"),
                ),
                (
                    "width",
                    models.FloatField(
                        default=20.0, help_text="Width in percentage (0-100)"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=10.0, help_text="Height in percentage (0-100)"
                    ),
                ),
                ("font_size", models.IntegerField(blank=True, default=14, null=True)),
                (
                    "font_family",
                    models.CharField(
                        blank=True,
                        default="Arial, sans-serif",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "font_weight",
                    models.CharField(
                        blank=True, default="normal", max_length=50, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="#000000", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(upload_to="certificate_templates/%Y/%m/%d/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="issued_certificates/%Y/%m/%d/"
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100, unique=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
