# Generated by Django 3.2.25 on 2025-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatetemplate_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('name', 'Name'), ('grade', 'Grade'), ('date', 'Date'), ('expiry_date', 'Expiry Date'), ('signature', 'Signature'), ('image', 'Image'), ('course', 'Course Name')], max_length=50),
        ),
    ]
