# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0001_initial"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchuserlimits",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who last updated these limits",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_branch_limits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="The business this branch belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="business.business",
            ),
        ),
        migrations.AddField(
            model_name="adminbranchassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Super admin who assigned this branch to the admin user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_admin_branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminbranchassignment",
            name="branch",
            field=models.ForeignKey(
                help_text="Branch assigned to the admin user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_admin_assignments",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="adminbranchassignment",
            name="user",
            field=models.ForeignKey(
                help_text="Admin user assigned to additional branch",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_branch_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminbranchassignment",
            index=models.Index(
                fields=["user", "is_active"], name="branches_ad_user_id_c99ff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminbranchassignment",
            index=models.Index(
                fields=["branch", "is_active"], name="branches_ad_branch__d07a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminbranchassignment",
            index=models.Index(
                fields=["assigned_by"], name="branches_ad_assigne_72fdc2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adminbranchassignment",
            unique_together={("user", "branch")},
        ),
    ]
