# Generated by Django 3.2.25 on 2025-10-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchuserlimits_total_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='teams_integration_enabled',
            field=models.BooleanField(default=False, help_text='Enable Microsoft Teams integration for this branch. Global admin can control this setting.'),
        ),
    ]
