# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_all_day", models.BooleanField(default=False)),
                ("color", models.CharField(default="#3498db", max_length=20)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "notification",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("15min", "15 minutes before"),
                            ("30min", "30 minutes before"),
                            ("1hour", "1 hour before"),
                            ("2hours", "2 hours before"),
                            ("1day", "1 day before"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#3498db", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Event Categories",
            },
        ),
    ]
