# Generated by Django 3.2.25 on 2025-10-18 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_learning_plan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatornote',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private notes only visible to staff'),
        ),
        migrations.AlterField(
            model_name='healthsafetydocument',
            name='document_file',
            field=models.FileField(help_text='Upload health & safety document (PDF, DOC, DOCX, TXT)', upload_to='health_safety_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='healthsafetysectiondocument',
            name='document_file',
            field=models.FileField(help_text='Upload document (PDF, DOC, DOCX, TXT, Images)', upload_to='health_safety_section_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='inductionchecklistdocument',
            name='document_file',
            field=models.FileField(help_text='Upload document (PDF, DOC, DOCX, TXT, Images)', upload_to='induction_section_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='inductiondocument',
            name='document_file',
            field=models.FileField(help_text='Upload induction document (PDF, DOC, DOCX, TXT)', upload_to='induction_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='learningneedssectiondocument',
            name='document_file',
            field=models.FileField(help_text='Upload document (PDF, DOC, DOCX, TXT, Images)', upload_to='learning_needs_section_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Upload evidence of progress', null=True, upload_to='ilp/progress_evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='statementofpurpose',
            name='sop_file',
            field=models.FileField(blank=True, help_text='Upload Statement of Purpose (PDF/Word, <5MB)', null=True, upload_to='ilp/sop_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='strengthsweaknessessectiondocument',
            name='document_file',
            field=models.FileField(help_text='Upload document (PDF, DOC, DOCX, TXT, Images)', upload_to='strengths_weaknesses_section_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
