# Generated by Django 3.2.25 on 2025-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='validity_days',
            field=models.IntegerField(default=0, help_text='Number of days the certificate is valid (0 = no expiry)'),
        ),
    ]
