# Generated by Django 3.2.25 on 2025-10-17 18:18

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificateelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='image',
            field=models.ImageField(storage=core.s3_storage.MediaS3Storage(), upload_to='certificate_templates/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, storage=core.s3_storage.MediaS3Storage(), upload_to='issued_certificates/%Y/%m/%d/'),
        ),
    ]
