# Generated by Django 3.2.25 on 2025-10-17 18:18

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20251001_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattachment',
            name='file',
            field=models.FileField(storage=core.s3_storage.MediaS3Storage(), upload_to='report_attachments/%Y/%m/%d/'),
        ),
    ]
