# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lms_messages", "0001_initial"),
        ("branches", "0002_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagereadstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_read_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="lms_messages.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch associated with this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_messages",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="The message this is a reply to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="lms_messages.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                help_text="The course this message is related to (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_messages",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sent_to_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group this message was sent to (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_messages",
                to="groups.branchgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["message", "user"], name="lms_message_message_558165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["user", "is_read"], name="lms_message_user_id_f919b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereadstatus",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["message", "uploaded_at"], name="lms_message_message_683896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="lms_message_sender__0f3d97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["external_id"], name="lms_message_externa_0c1d89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["branch"], name="lms_message_branch__36973f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sent_to_group"], name="lms_message_sent_to_51cdd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["related_course"], name="lms_message_related_3f9d4a_idx"
            ),
        ),
    ]
