# Generated by Django 3.2.25 on 2025-10-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0007_change_scorm_cascade'),
        ('courses', '0003_add_scorm_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Document', 'Document'), ('Text', 'Text'), ('Audio', 'Audio'), ('Web', 'Web Content'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('EmbedVideo', 'Embedded Video'), ('Conference', 'ILT/Conference'), ('Discussion', 'Discussion'), ('SCORM', 'SCORM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='scorm',
            field=models.ForeignKey(blank=True, help_text='Associated SCORM package for SCORM type topics', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='scorm.scormpackage'),
        ),
    ]
