# Generated by Django 3.2.25 on 2025-10-01 15:48

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_topic_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='Whether this course is temporary'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload file for Video, Audio, Document content (SCORM goes directly to SCORM Cloud)', max_length=255, null=True, upload_to=courses.models.content_file_path),
        ),
    ]
