# Generated by Django 3.2.25 on 2025-11-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_course_field(apps, schema_editor):
    """
    Populate the course field for existing TopicProgress records.
    For records where a topic belongs to only one course, use that course.
    For topics in multiple courses, we'll need to handle duplicates.
    """
    TopicProgress = apps.get_model('courses', 'TopicProgress')
    CourseTopic = apps.get_model('courses', 'CourseTopic')
    
    # Get all TopicProgress records without a course
    progress_records = TopicProgress.objects.filter(course__isnull=True)
    
    for progress in progress_records:
        # Find courses that contain this topic
        course_topics = CourseTopic.objects.filter(topic=progress.topic)
        
        if course_topics.count() == 1:
            # Topic belongs to only one course - straightforward
            progress.course = course_topics.first().course
            progress.save(update_fields=['course'])
        elif course_topics.count() > 1:
            # Topic is shared across multiple courses
            # We need to duplicate the progress record for each course
            first_course_topic = course_topics.first()
            # Use the first course for the existing record
            progress.course = first_course_topic.course
            progress.save(update_fields=['course'])
            
            # Create duplicate records for other courses
            for course_topic in course_topics[1:]:
                TopicProgress.objects.create(
                    user=progress.user,
                    topic=progress.topic,
                    course=course_topic.course,
                    progress_data=progress.progress_data,
                    bookmark=progress.bookmark,
                    completion_data=progress.completion_data,
                    completed=progress.completed,
                    completion_method=progress.completion_method,
                    manually_completed=progress.manually_completed,
                    attempts=progress.attempts,
                    last_score=progress.last_score,
                    best_score=progress.best_score,
                    total_time_spent=0,  # Reset time for new course context
                    audio_progress=progress.audio_progress,
                    last_audio_position=progress.last_audio_position,
                    completed_at=progress.completed_at,
                )


def reverse_populate_course_field(apps, schema_editor):
    """Reverse migration - remove course associations"""
    TopicProgress = apps.get_model('courses', 'TopicProgress')
    # Simply set course to None for all records
    TopicProgress.objects.all().update(course=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_change_scorm_cascade'),
    ]

    operations = [
        # Step 1: Add the field (nullable)
        migrations.AddField(
            model_name='topicprogress',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course context for this progress tracking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='courses.course'),
        ),
        # Step 2: Populate existing data
        migrations.RunPython(populate_course_field, reverse_populate_course_field),
        # Step 3: Add constraints and indexes
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together={('user', 'topic', 'course')},
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['user', 'topic', 'course'], name='courses_top_user_id_028084_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['course', 'user'], name='courses_top_course__a363ac_idx'),
        ),
    ]
