# Generated by Django 3.2.25 on 2025-10-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scorm_mastery_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mastery score for SCORM content (0-100)', max_digits=5, null=True),
        ),
    ]
