# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_preserve_discussion_on_topic_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDiscussionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='discussion_attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_comment_attachments', to='courses.comment')),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_attachments', to='courses.discussion')),
            ],
            options={
                'verbose_name': 'Topic Discussion Attachment',
                'verbose_name_plural': 'Topic Discussion Attachments',
                'db_table': 'courses_attachment',
            },
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='source_course',
            field=models.ForeignKey(blank=True, help_text='The course that caused this auto-enrollment (for prerequisite relationships)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddIndex(
            model_name='topicdiscussionattachment',
            index=models.Index(fields=['discussion'], name='courses_att_discuss_a83549_idx'),
        ),
        migrations.AddIndex(
            model_name='topicdiscussionattachment',
            index=models.Index(fields=['comment'], name='courses_att_comment_61debf_idx'),
        ),
        migrations.AddIndex(
            model_name='topicdiscussionattachment',
            index=models.Index(fields=['-uploaded_at'], name='courses_att_uploade_af38b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicdiscussionattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('comment__isnull', True), ('discussion__isnull', False)), models.Q(('comment__isnull', False), ('discussion__isnull', True)), _connector='OR'), name='courses_attachment_exclusive_parent'),
        ),
    ]
