# Generated by Django 3.2.25 on 2025-10-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_scorm_mastery_score'),
        ('branches', '0001_initial'),
        ('categories', '0001_initial'),
        ('course_reviews', '0001_initial'),
        ('certificates', '0001_initial'),
        ('users', '0002_auto_20251022_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses',
                to='branches.branch'
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses',
                to='categories.coursecategory'
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='survey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses',
                to='course_reviews.survey'
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='courses',
                to='certificates.certificatetemplate'
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='instructed_courses',
                to='users.customuser'
            ),
        ),
    ]
