# Generated by Django 3.2.25 on 2025-10-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20251022_0734'),
        ('scorm', '0008_auto_20251022_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='scorm_registration',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='topic_progress',
                to='scorm.scormattempt'
            ),
        ),
    ]
