# Generated by Django 3.2.25 on 2025-10-22 14:52

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchuserlimits_total_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_reviews', '0002_increase_char_limits_to_800'),
        ('certificates', '0004_alter_certificateelement_element_type'),
        ('courses', '0009_auto_20251022_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicprogress',
            name='scorm_registration',
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='scorm_registration_id',
            field=models.BigIntegerField(blank=True, help_text='SCORM Cloud registration ID', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this course belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, help_text='Certificate template to use for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='certificates.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, help_text='Course thumbnail image', max_length=800, null=True, upload_to=courses.models.course_image_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, help_text='Course introduction video', max_length=800, null=True, upload_to=courses.models.course_video_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(help_text='The instructor assigned to this course.', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Survey to be completed by learners after finishing this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course_reviews.survey'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_file',
            field=models.FileField(blank=True, help_text='Upload file for Video, Audio, Document content', max_length=800, null=True, upload_to=courses.models.content_file_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='topic',
            name='web_url',
            field=models.URLField(blank=True, help_text='URL for Web Content type topics', max_length=800, null=True),
        ),
    ]
