# Generated by Django 3.2.25 on 2025-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_increase_char_limits_to_800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecompletionrequirement',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='coursecompletionrequirement',
            name='requirement_type',
            field=models.CharField(default='score_threshold', help_text="Type of requirement (e.g., 'topic_completion', 'score_threshold')", max_length=100),
        ),
        migrations.AddField(
            model_name='coursecompletionrequirement',
            name='requirement_value',
            field=models.TextField(default='0', help_text='Value or configuration for the requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecompletionrequirement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursecompletionrequirement',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='coursecompletionrequirement',
            name='required_score',
        ),
        migrations.RemoveField(
            model_name='coursecompletionrequirement',
            name='topic',
        ),
    ]
