# Generated by Django 3.2.25 on 2025-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(
                blank=True,
                help_text='Courses that must be completed before enrolling',
                related_name='required_for',
                symmetrical=False,
                to='courses.Course'
            ),
        ),
    ]
