# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminBranchAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this assignment is active"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this assignment",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Branch Assignment",
                "verbose_name_plural": "Admin Branch Assignments",
                "ordering": ["user__username", "branch__name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sharepoint_integration_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable SharePoint integration for this branch. Global admin can control this setting.",
                    ),
                ),
                (
                    "order_management_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable order management features for this branch. Global admin can control this setting.",
                    ),
                ),
                (
                    "scorm_integration_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable SCORM integration for this branch. Admin can control this setting.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["business__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="BranchUserLimits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_limit",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of users allowed in this branch",
                    ),
                ),
                (
                    "admin_limit",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of admin users allowed in this branch",
                    ),
                ),
                (
                    "instructor_limit",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum number of instructor users allowed in this branch",
                    ),
                ),
                (
                    "learner_limit",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Maximum number of learner users allowed in this branch",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        help_text="The branch these limits apply to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_user_limits",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch User Limits",
                "verbose_name_plural": "Branch User Limits",
                "ordering": ["branch__name"],
            },
        ),
    ]
