# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicassignment",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.topic"
            ),
        ),
    ]
