# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_topicassignment_topic'),
        ('lms_rubrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmissioniterationfeedback',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_field_iteration_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textsubmissioniterationfeedback',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assignments.textsubmissionansweriteration'),
        ),
        migrations.AddField(
            model_name='textsubmissionfield',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='textsubmissionansweriteration',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_iterations', to='assignments.textsubmissionfield'),
        ),
        migrations.AddField(
            model_name='textsubmissionansweriteration',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_answer_iterations', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='textsubmissionanswer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.textsubmissionfield'),
        ),
        migrations.AddField(
            model_name='textsubmissionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_answers', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='textquestioniterationfeedback',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_question_iteration_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textquestioniterationfeedback',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assignments.textquestionansweriteration'),
        ),
        migrations.AddField(
            model_name='textquestionansweriteration',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_iterations', to='assignments.textquestion'),
        ),
        migrations.AddField(
            model_name='textquestionansweriteration',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answer_iterations', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='textquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.textquestion'),
        ),
        migrations.AddField(
            model_name='textquestionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_questions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='supportingdocquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_doc_questions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='supportingdocquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_doc_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assignments.supportingdocquestion'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='filesubmissioniterationfeedback',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_file_iteration_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filesubmissioniterationfeedback',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assignments.filesubmissioniteration'),
        ),
        migrations.AddField(
            model_name='filesubmissioniteration',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_iterations', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsessionlog',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsessionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentreportconfirmation',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_confirmations', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentreportconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentreportconfirmation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentinteractionlog',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentinteractionlog',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Related submission if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentinteractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentfeedback',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentfeedback',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentcourse',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='assignment',
            field=models.ForeignKey(help_text='The assignment this comment is related to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='author',
            field=models.ForeignKey(help_text='The user who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='assignments.assignmentcomment'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='The specific submission this comment is related to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_assignments', through='assignments.AssignmentCourse', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(blank=True, help_text='Rubric used for grading this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lms_rubrics.rubric'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topic_assignments', through='assignments.TopicAssignment', to='courses.Topic'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapprovalhistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approval_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapprovalhistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_approval_history', to='assignments.assignmentsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='topicassignment',
            unique_together={('topic', 'assignment')},
        ),
        migrations.AddIndex(
            model_name='textsubmissioniterationfeedback',
            index=models.Index(fields=['iteration', '-created_at'], name='assignments_iterati_918ead_idx'),
        ),
        migrations.AddIndex(
            model_name='textsubmissionfield',
            index=models.Index(fields=['assignment', 'order'], name='assignments_assignm_3df085_idx'),
        ),
        migrations.AddIndex(
            model_name='textsubmissionansweriteration',
            index=models.Index(fields=['field', 'submission', 'iteration_number'], name='assignments_field_i_4b0dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='textsubmissionansweriteration',
            index=models.Index(fields=['field', 'submission', '-iteration_number'], name='assignments_field_i_0edad4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textsubmissionansweriteration',
            unique_together={('field', 'submission', 'iteration_number')},
        ),
        migrations.AlterUniqueTogether(
            name='textsubmissionanswer',
            unique_together={('field', 'submission')},
        ),
        migrations.AddIndex(
            model_name='textquestioniterationfeedback',
            index=models.Index(fields=['iteration', '-created_at'], name='assignments_iterati_aa502d_idx'),
        ),
        migrations.AddIndex(
            model_name='textquestionansweriteration',
            index=models.Index(fields=['question', 'submission', 'iteration_number'], name='assignments_questio_9bd745_idx'),
        ),
        migrations.AddIndex(
            model_name='textquestionansweriteration',
            index=models.Index(fields=['question', 'submission', '-iteration_number'], name='assignments_questio_8aef78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textquestionansweriteration',
            unique_together={('question', 'submission', 'iteration_number')},
        ),
        migrations.AlterUniqueTogether(
            name='textquestionanswer',
            unique_together={('question', 'submission')},
        ),
        migrations.AddIndex(
            model_name='textquestion',
            index=models.Index(fields=['assignment', 'order'], name='assignments_assignm_8214b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('question', 'student')},
        ),
        migrations.AddIndex(
            model_name='filesubmissioniterationfeedback',
            index=models.Index(fields=['iteration', '-created_at'], name='assignments_iterati_f8a5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='filesubmissioniteration',
            index=models.Index(fields=['submission', 'iteration_number'], name='assignments_submiss_fba67f_idx'),
        ),
        migrations.AddIndex(
            model_name='filesubmissioniteration',
            index=models.Index(fields=['submission', '-iteration_number'], name='assignments_submiss_8290dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filesubmissioniteration',
            unique_together={('submission', 'iteration_number')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'user')},
        ),
        migrations.AddIndex(
            model_name='assignmentsessionlog',
            index=models.Index(fields=['assignment', 'user', '-start_time'], name='assignments_assignm_e3b93f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsessionlog',
            index=models.Index(fields=['session_key', 'is_active'], name='assignments_session_36c237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentreportconfirmation',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='assignmentinteractionlog',
            index=models.Index(fields=['assignment', 'user', '-created_at'], name='assignments_assignm_46fc63_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentinteractionlog',
            index=models.Index(fields=['interaction_type', '-created_at'], name='assignments_interac_6e7747_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentinteractionlog',
            index=models.Index(fields=['user', '-created_at'], name='assignments_user_id_df07fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentcourse',
            unique_together={('assignment', 'course')},
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['assignment', 'created_at'], name='assignments_assignm_8b0a16_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['submission', 'created_at'], name='assignments_submiss_3772c3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['author', 'created_at'], name='assignments_author__cd682c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', '-created_at'], name='assignments_course__45b6d6_idx'),
        ),
    ]
