# Generated by Django 3.2.25 on 2025-11-07 16:48

from django.db import migrations, models
import assignments.models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmissioniteration',
            name='file',
            field=models.FileField(help_text='The uploaded file for this iteration', max_length=500, upload_to=assignments.models.assignment_file_path),
        ),
    ]
