# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_rubrics', '0002_initial'),
        ('assignments', '0005_increase_all_file_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='assignments_course__45b6d6_idx',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(blank=True, help_text='Rubric used for grading this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_assignments', to='lms_rubrics.rubric'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['-created_at'], name='assignments_created_00ae20_idx'),
        ),
    ]
