# Generated by Django 3.2.25 on 2025-10-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0036_update_feedback_labels'),
        ('courses', '0007_course_scorm_mastery_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignments',
                to='courses.course'
            ),
        ),
    ]
