# Generated by Django 3.2.25 on 2025-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0037_alter_assignment_attachment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='assignments_course__45b6d6_idx',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['-created_at'], name='assignments_created_00ae20_idx'),
        ),
    ]
