# Generated by Django 3.2.25 on 2025-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0037_auto_20251022_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type of the attachment', max_length=500, null=True),
        ),
    ]
