# Generated by Django 3.2.25 on 2025-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0038_auto_20251022_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapprovalhistory',
            name='trigger_reason',
            field=models.CharField(blank=True, help_text="What triggered this approval review (e.g., 'new_feedback', 'file_resubmission', 'text_revision')", max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allowed_file_types',
            field=models.CharField(default='.pdf,.doc,.docx,.txt,.ppt,.pptx,.mp4,.mov,.avi,.wmv', help_text='Comma-separated list of allowed file extensions', max_length=800),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type of the attachment', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_file_size',
            field=models.IntegerField(default=629145600, help_text='Maximum file size in bytes'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='assignmentattachment',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type of the attachment', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='filesubmissioniteration',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='filesubmissioniteration',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='textsubmissionfield',
            name='label',
            field=models.CharField(help_text='Label for the text field', max_length=800),
        ),
        migrations.AlterField(
            model_name='textsubmissionfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for the field', max_length=800),
        ),
    ]
