# Generated by Django 3.2.25 on 2025-10-22 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_record', to='assignments.assignmentsubmission'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'assignment'], name='gradebook_g_student_b12442_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['course', 'student'], name='gradebook_g_course__309da6_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['assignment', 'score'], name='gradebook_g_assignm_407b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['created_at'], name='gradebook_g_created_da59bc_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['updated_at'], name='gradebook_g_updated_3131aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assignment')},
        ),
    ]
