# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gradebook', '0003_remove_course_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'assignment'], name='gradebook_g_student_b12442_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['assignment', '-created_at'], name='gradebook_g_assignm_fc0422_idx'),
        ),
    ]
