# Generated by Django 3.2.25 on 2025-10-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0004_auto_20251015_1718'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'assignment'], name='gradebook_g_student_b12442_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['course', 'student'], name='gradebook_g_course__309da6_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['assignment', 'score'], name='gradebook_g_assignm_407b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['created_at'], name='gradebook_g_created_da59bc_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['updated_at'], name='gradebook_g_updated_3131aa_idx'),
        ),
    ]
