# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuserassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Global admin who assigned this user to the business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessuserassignment',
            name='business',
            field=models.ForeignKey(help_text='The business this user is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='business.business'),
        ),
        migrations.AddField(
            model_name='businessuserassignment',
            name='user',
            field=models.ForeignKey(help_text='The super admin user assigned to this business', on_delete=django.db.models.deletion.CASCADE, related_name='business_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesslimits',
            name='business',
            field=models.OneToOneField(help_text='The business these limits apply to', on_delete=django.db.models.deletion.CASCADE, related_name='business_limits', to='business.business'),
        ),
        migrations.AddField(
            model_name='businesslimits',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Global admin who last updated these limits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_business_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='businessuserassignment',
            unique_together={('business', 'user')},
        ),
    ]
