# Generated by Django 3.2.25 on 2025-10-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuserassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Global admin who assigned this user to the business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_business_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessuserassignment',
            name='business',
            field=models.ForeignKey(help_text='The business this user is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='business_user_assignments', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessuserassignment',
            name='user',
            field=models.ForeignKey(help_text='The super admin user assigned to this business', on_delete=django.db.models.deletion.CASCADE, related_name='user_business_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
