# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("role_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who assigned this role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="role_management.role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolecapability",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this capability",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_capabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolecapability",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capabilities",
                to="role_management.role",
            ),
        ),
        migrations.AddField(
            model_name="roleauditlog",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="role_management.role",
            ),
        ),
        migrations.AddField(
            model_name="roleauditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_audit_target_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "role"], name="role_manage_user_id_df74a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user"], name="role_manage_user_id_d9079b_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="role_manage_role_id_60f346_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["is_active"], name="role_manage_is_acti_2b2c21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["expires_at"], name="role_manage_expires_616573_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
        migrations.AddIndex(
            model_name="rolecapability",
            index=models.Index(
                fields=["role", "capability"], name="role_manage_role_id_cdfd7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolecapability",
            index=models.Index(
                fields=["capability"], name="role_manage_capabil_e016aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolecapability",
            index=models.Index(
                fields=["is_active"], name="role_manage_is_acti_434536_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolecapability",
            unique_together={("role", "capability")},
        ),
        migrations.AddIndex(
            model_name="roleauditlog",
            index=models.Index(
                fields=["timestamp"], name="role_manage_timesta_aba25a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleauditlog",
            index=models.Index(fields=["user"], name="role_manage_user_id_28783d_idx"),
        ),
        migrations.AddIndex(
            model_name="roleauditlog",
            index=models.Index(fields=["role"], name="role_manage_role_id_d4661f_idx"),
        ),
        migrations.AddIndex(
            model_name="roleauditlog",
            index=models.Index(fields=["action"], name="role_manage_action_8f52c7_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name"], name="role_manage_name_e5dec9_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_active"], name="role_manage_is_acti_c73a2f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_name__isnull", False)),
                fields=("custom_name",),
                name="unique_custom_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "name__in",
                        ["globaladmin", "superadmin", "admin", "instructor", "learner"],
                    )
                ),
                fields=("name",),
                name="unique_non_custom_roles",
            ),
        ),
    ]
