# Generated by Django 3.2.25 on 2025-10-07 02:11

from django.db import migrations


def populate_default_roles(apps, schema_editor):
    """
    Populate default roles and their capabilities.
    This ensures the role management system has all necessary default roles.
    """
    Role = apps.get_model('role_management', 'Role')
    RoleCapability = apps.get_model('role_management', 'RoleCapability')

    # Define default roles
    default_roles_data = {
        'globaladmin': {
            'description': 'Global Administrator with system-wide access and control over all businesses, branches, and users.',
            'capabilities': [
                # Global Admin has ALL capabilities plus special system controls
                'view_users', 'manage_users', 'create_users', 'delete_users',
                'view_courses', 'manage_courses', 'create_courses', 'delete_courses',
                'view_assignments', 'manage_assignments', 'grade_assignments', 'create_assignments', 'delete_assignments',
                'manage_roles', 'view_roles', 'create_roles', 'delete_roles',
                'view_groups', 'manage_groups', 'manage_group_members', 'create_groups', 'delete_groups',
                'view_branches', 'manage_branches', 'create_branches', 'delete_branches',
                'view_topics', 'manage_topics', 'create_topics', 'delete_topics',
                'view_quizzes', 'manage_quizzes', 'grade_quizzes', 'create_quizzes', 'delete_quizzes',
                'view_progress', 'manage_progress',
                'view_reports', 'manage_reports', 'export_reports', 'view_analytics',
                'manage_system_settings', 'view_system_logs',
                'manage_notifications', 'send_notifications',
                'create_messages', 'manage_messages', 'view_messages', 'delete_messages',
                'view_categories', 'manage_categories', 'create_categories', 'delete_categories',
                'view_certificates_templates', 'manage_certificates',
                'view_rubrics', 'manage_rubrics', 'create_rubrics', 'delete_rubrics',
                'view_discussions', 'manage_discussions', 'create_discussions', 'delete_discussions',
                'view_conferences', 'manage_conferences', 'create_conferences', 'delete_conferences',
                # SCORM Management
                'view_scorm', 'manage_scorm', 'create_scorm', 'delete_scorm', 'track_scorm_progress',
                # Outcomes Management
                'view_outcomes', 'manage_outcomes', 'create_outcomes', 'delete_outcomes', 'align_outcomes',
                # Gradebook Management
                'view_gradebook', 'manage_gradebook', 'export_gradebook', 'import_gradebook',
                # Calendar Management
                'view_calendar', 'manage_calendar', 'create_calendar_events', 'delete_calendar_events',
                # Individual Learning Plans
                'view_ilp', 'manage_ilp', 'create_ilp', 'delete_ilp', 'assign_ilp',
                # Media Management
                'view_media', 'manage_media', 'upload_media', 'delete_media',
                # Course Reviews
                'view_course_reviews', 'manage_course_reviews', 'delete_course_reviews', 'moderate_reviews',
                # SharePoint Integration
                'view_sharepoint', 'manage_sharepoint_integration', 'sync_sharepoint',
                # Account Settings
                'view_account_settings', 'manage_account_settings', 'manage_global_admin_settings',
                # Business Management
                'view_business', 'manage_business', 'create_business', 'delete_business',
                # Global Admin exclusive capabilities
                'manage_global_settings', 'manage_oauth_configuration', 'manage_menu_control',
                'manage_ai_settings', 'system_wide_administration', 'global_menu_visibility',
                'configure_google_oauth', 'manage_all_integrations', 'global_feature_control'
            ]
        },
        'superadmin': {
            'description': 'Super Administrator with business-level access and control over assigned businesses and branches.',
            'capabilities': [
                'view_users', 'manage_users', 'create_users', 'delete_users',
                'view_courses', 'manage_courses', 'create_courses', 'delete_courses',
                'view_assignments', 'manage_assignments', 'grade_assignments', 'create_assignments', 'delete_assignments',
                'view_groups', 'manage_groups', 'manage_group_members', 'create_groups', 'delete_groups',
                'view_branches', 'manage_branches', 'create_branches', 'delete_branches',
                'view_topics', 'manage_topics', 'create_topics', 'delete_topics',
                'view_quizzes', 'manage_quizzes', 'grade_quizzes', 'create_quizzes', 'delete_quizzes',
                'view_progress', 'manage_progress',
                'view_reports', 'manage_reports', 'export_reports',
                'manage_system_settings', 'view_system_logs',
                'manage_notifications', 'send_notifications',
                'create_messages', 'manage_messages', 'view_messages',
                'view_categories', 'manage_categories', 'create_categories', 'delete_categories',
                'view_certificates_templates', 'manage_certificates',
                # SCORM Management
                'view_scorm', 'manage_scorm', 'create_scorm', 'delete_scorm', 'track_scorm_progress',
                # Outcomes Management
                'view_outcomes', 'manage_outcomes', 'create_outcomes', 'delete_outcomes', 'align_outcomes',
                # Gradebook Management
                'view_gradebook', 'manage_gradebook', 'export_gradebook', 'import_gradebook',
                # Calendar Management
                'view_calendar', 'manage_calendar', 'create_calendar_events', 'delete_calendar_events',
                # Individual Learning Plans
                'view_ilp', 'manage_ilp', 'create_ilp', 'delete_ilp', 'assign_ilp',
                # Media Management
                'view_media', 'manage_media', 'upload_media', 'delete_media',
                # Course Reviews
                'view_course_reviews', 'manage_course_reviews', 'delete_course_reviews', 'moderate_reviews',
                # SharePoint Integration
                'view_sharepoint', 'manage_sharepoint_integration', 'sync_sharepoint',
                # Account Settings
                'view_account_settings', 'manage_account_settings',
                # Business Management
                'view_business', 'manage_business'
            ]
        },
        'admin': {
            'description': 'Branch Administrator with branch-level access and control over branch users and content.',
            'capabilities': [
                'view_users', 'manage_users', 'create_users', 'delete_users',
                'view_courses', 'manage_courses', 'create_courses', 'delete_courses',
                'view_assignments', 'manage_assignments', 'grade_assignments', 'create_assignments', 'delete_assignments',
                'view_groups', 'manage_groups', 'manage_group_members', 'create_groups', 'delete_groups',
                'view_branches', 'manage_branches', 'create_branches', 'delete_branches',
                'view_topics', 'manage_topics', 'create_topics', 'delete_topics',
                'view_quizzes', 'manage_quizzes', 'grade_quizzes', 'create_quizzes', 'delete_quizzes',
                'view_progress', 'manage_progress',
                'view_reports', 'manage_reports', 'export_reports',
                'manage_notifications', 'send_notifications',
                'create_messages', 'manage_messages', 'view_messages',
                'view_categories', 'manage_categories', 'create_categories', 'delete_categories',
                'view_certificates_templates', 'manage_certificates',
                # SCORM Management
                'view_scorm', 'manage_scorm', 'create_scorm', 'track_scorm_progress',
                # Outcomes Management
                'view_outcomes', 'manage_outcomes', 'create_outcomes', 'align_outcomes',
                # Gradebook Management
                'view_gradebook', 'manage_gradebook', 'export_gradebook', 'import_gradebook',
                # Calendar Management
                'view_calendar', 'manage_calendar', 'create_calendar_events', 'delete_calendar_events',
                # Individual Learning Plans
                'view_ilp', 'manage_ilp', 'create_ilp', 'assign_ilp',
                # Media Management
                'view_media', 'manage_media', 'upload_media',
                # Course Reviews
                'view_course_reviews', 'manage_course_reviews', 'moderate_reviews',
                # Account Settings
                'view_account_settings'
            ]
        },
        'instructor': {
            'description': 'Instructor with ability to create and manage courses, assignments, and grade students.',
            'capabilities': [
                'view_users',
                'view_courses', 'manage_courses', 'create_courses',
                'view_assignments', 'manage_assignments', 'grade_assignments', 'create_assignments',
                'view_groups',
                'view_branches',
                'view_topics', 'manage_topics', 'create_topics',
                'view_quizzes', 'manage_quizzes', 'grade_quizzes', 'create_quizzes',
                'view_progress', 'manage_progress',
                'create_messages', 'manage_messages', 'view_messages',
                'view_reports',
                'view_categories',
                'view_certificates_templates', 'manage_certificates',
                # SCORM Management
                'view_scorm', 'manage_scorm', 'create_scorm', 'track_scorm_progress',
                # Outcomes Management
                'view_outcomes', 'manage_outcomes', 'align_outcomes',
                # Gradebook Management
                'view_gradebook', 'manage_gradebook', 'export_gradebook',
                # Calendar Management
                'view_calendar', 'create_calendar_events',
                # Individual Learning Plans
                'view_ilp', 'manage_ilp', 'assign_ilp',
                # Media Management
                'view_media', 'upload_media',
                # Course Reviews
                'view_course_reviews',
                # Account Settings
                'view_account_settings'
            ]
        },
        'learner': {
            'description': 'Learner with access to view courses, submit assignments, and take quizzes.',
            'capabilities': [
                'view_users',
                'view_courses',
                'view_assignments', 'submit_assignments',
                'view_groups',
                'view_branches',
                'view_topics',
                'view_quizzes', 'take_quizzes',
                'view_progress',
                'view_messages', 'create_messages',
                'view_certificates_templates',
                'view_reports',
                'view_categories',
                # SCORM Management
                'view_scorm', 'track_scorm_progress',
                # Outcomes Management
                'view_outcomes',
                # Gradebook Management
                'view_gradebook',
                # Calendar Management
                'view_calendar',
                # Individual Learning Plans
                'view_ilp',
                # Media Management
                'view_media',
                # Course Reviews
                'view_course_reviews',
                # Account Settings
                'view_account_settings'
            ]
        }
    }

    # Create roles and capabilities
    for role_name, role_info in default_roles_data.items():
        # Create or get the role
        role, created = Role.objects.get_or_create(
            name=role_name,
            defaults={
                'description': role_info['description'],
                'is_active': True,
            }
        )

        # Create capabilities for this role
        for capability in role_info['capabilities']:
            RoleCapability.objects.get_or_create(
                role=role,
                capability=capability,
                defaults={
                    'description': f'{capability.replace("_", " ").title()} capability',
                    'is_active': True,
                }
            )


def reverse_populate_roles(apps, schema_editor):
    """
    Reverse migration - remove default roles and their capabilities.
    Only removes roles if they have no user assignments.
    """
    Role = apps.get_model('role_management', 'Role')
    UserRole = apps.get_model('role_management', 'UserRole')

    default_role_names = ['globaladmin', 'superadmin', 'admin', 'instructor', 'learner']
    
    for role_name in default_role_names:
        try:
            role = Role.objects.get(name=role_name)
            # Only delete if no users are assigned to this role
            if not UserRole.objects.filter(role=role).exists():
                role.delete()
        except Role.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_default_roles, reverse_populate_roles),
    ]
