# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account_settings", "0003_initial"),
        ("sharepoint_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharepointsynclog",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharepointsynclog",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="account_settings.sharepointintegration",
            ),
        ),
        migrations.AddField(
            model_name="sharepointconflict",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="account_settings.sharepointintegration",
            ),
        ),
    ]
