# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0001_initial"),
        ("lms_rubrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencerubricevaluation",
            name="criterion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_evaluations",
                to="lms_rubrics.rubriccriterion",
            ),
        ),
    ]
