# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("lms_rubrics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account_settings", "0003_initial"),
        ("branches", "0002_initial"),
        ("conferences", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencerubricevaluation",
            name="evaluated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conference_rubric_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conferencerubricevaluation",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conference_evaluations",
                to="lms_rubrics.rubricrating",
            ),
        ),
        migrations.AddField(
            model_name="conferencerecording",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="conferences.conference",
            ),
        ),
        migrations.AddField(
            model_name="conferenceparticipant",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="conferences.conference",
            ),
        ),
        migrations.AddField(
            model_name="conferenceparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conferencefile",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_files",
                to="conferences.conference",
            ),
        ),
        migrations.AddField(
            model_name="conferencefile",
            name="shared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_conference_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conferencechat",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="conferences.conference",
            ),
        ),
        migrations.AddField(
            model_name="conferencechat",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conferenceattendance",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="conferences.conference",
            ),
        ),
        migrations.AddField(
            model_name="conferenceattendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conference_attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conferences",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional rubric for this conference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conferences",
                to="lms_rubrics.rubric",
            ),
        ),
        migrations.AddField(
            model_name="branchzoomaccess",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zoom_access_permissions",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="branchzoomaccess",
            name="zoom_integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_permissions",
                to="account_settings.zoomintegration",
            ),
        ),
        migrations.AddIndex(
            model_name="participanttrackingdata",
            index=models.Index(
                fields=["participant", "data_type"],
                name="conferences_partici_fa539b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="participanttrackingdata",
            index=models.Index(
                fields=["recorded_at"], name="conferences_recorde_cf7d57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participanttrackingdata",
            index=models.Index(
                fields=["synced_at"], name="conferences_synced__67a67b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participanttrackingdata",
            index=models.Index(
                fields=["data_quality_score"], name="conferences_data_qu_f75463_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participanttrackingdata",
            unique_together={("participant", "data_type", "recorded_at")},
        ),
        migrations.AddIndex(
            model_name="guestparticipant",
            index=models.Index(
                fields=["conference", "participation_id"],
                name="conferences_confere_faea54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guestparticipant",
            index=models.Index(
                fields=["participation_id"], name="conferences_partici_f71ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestparticipant",
            index=models.Index(
                fields=["join_time"], name="conferences_join_ti_f4a0d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestparticipant",
            index=models.Index(
                fields=["participation_status"], name="conferences_partici_e58d6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencesynclog",
            index=models.Index(
                fields=["conference"], name="conferences_confere_b5db12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencesynclog",
            index=models.Index(
                fields=["sync_type"], name="conferences_sync_ty_7f0023_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencesynclog",
            index=models.Index(fields=["status"], name="conferences_status_a618b8_idx"),
        ),
        migrations.AddIndex(
            model_name="conferencesynclog",
            index=models.Index(
                fields=["started_at"], name="conferences_started_ed16be_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conferencerubricevaluation",
            unique_together={("attendance", "criterion")},
        ),
        migrations.AddIndex(
            model_name="conferencerecording",
            index=models.Index(
                fields=["conference"], name="conferences_confere_1a2a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencerecording",
            index=models.Index(
                fields=["recording_id"], name="conferences_recordi_ed496c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencerecording",
            index=models.Index(fields=["status"], name="conferences_status_ed7ff4_idx"),
        ),
        migrations.AddIndex(
            model_name="conferencerecording",
            index=models.Index(
                fields=["created_at"], name="conferences_created_edca33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["conference", "user"], name="conferences_confere_b3ab14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["participant_id"], name="conferences_partici_05fdcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["session_token"], name="conferences_session_f44e21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["participation_status"], name="conferences_partici_e73ef4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["click_timestamp"], name="conferences_click_t_9546be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["platform_participant_id"],
                name="conferences_platfor_5b7ef2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceparticipant",
            index=models.Index(
                fields=["sync_status"], name="conferences_sync_st_23334d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conferenceparticipant",
            unique_together={("conference", "user", "participant_id")},
        ),
        migrations.AddIndex(
            model_name="conferencefile",
            index=models.Index(
                fields=["conference"], name="conferences_confere_8f1dc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencefile",
            index=models.Index(
                fields=["shared_by"], name="conferences_shared__64d905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencefile",
            index=models.Index(
                fields=["shared_at"], name="conferences_shared__6f7d56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencefile",
            index=models.Index(
                fields=["file_type"], name="conferences_file_ty_74d045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencechat",
            index=models.Index(
                fields=["conference"], name="conferences_confere_ed3e27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencechat",
            index=models.Index(
                fields=["sender"], name="conferences_sender__12be69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencechat",
            index=models.Index(
                fields=["sent_at"], name="conferences_sent_at_012829_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferencechat",
            index=models.Index(
                fields=["message_type"], name="conferences_message_2665cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceattendance",
            index=models.Index(
                fields=["conference", "user"], name="conferences_confere_e794c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceattendance",
            index=models.Index(
                fields=["attendance_status"], name="conferences_attenda_cf6bf7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceattendance",
            index=models.Index(
                fields=["join_time"], name="conferences_join_ti_7a85a4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conferenceattendance",
            unique_together={("conference", "user")},
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["date", "start_time"], name="conferences_date_7a7e4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["created_by"], name="conferences_created_3aeb5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["course"], name="conferences_course__eec8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(fields=["status"], name="conferences_status_3ba729_idx"),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["meeting_status"], name="conferences_meeting_275732_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["data_sync_status"], name="conferences_data_sy_6ec13b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["auto_recording_status"], name="conferences_auto_re_5f379e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchzoomaccess",
            index=models.Index(
                fields=["branch"], name="conferences_branch__0cfc1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchzoomaccess",
            index=models.Index(
                fields=["zoom_integration"], name="conferences_zoom_in_d9d5c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchzoomaccess",
            unique_together={("branch", "zoom_integration")},
        ),
    ]
