# Generated by Django 3.2.25 on 2025-10-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='diagnostic_assessment_english_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='diagnostic_assessment_maths_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='diagnostic_assessment_other_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='diagnostic_assessment_subject_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='functional_skills_english_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='functional_skills_maths_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='functional_skills_other_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initial_assessment_english_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initial_assessment_maths_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initial_assessment_other_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initial_assessment_subject_score',
        ),
    ]
