# Generated by Django 3.2.25 on 2025-10-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_legacy_score_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_sta',
            new_name='is_staff',
        ),
    ]
