# Generated by Django 3.2.25 on 2025-10-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branchuserlimits_total_limit'),
        ('users', '0003_rename_is_sta_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to this learner.', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user belongs to. Not required for Global Admin users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_users', to='branches.branch'),
        ),
    ]
