# Generated by Django 3.2.25 on 2025-10-16 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.URLField()),
                ('profile_id', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('content_type', models.CharField(default='application/json', max_length=100)),
                ('etag', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.JSONField(default=dict)),
                ('profile_id', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('content_type', models.CharField(default='application/json', max_length=100)),
                ('etag', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMI5AU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('launch_url', models.URLField()),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('move_on', models.CharField(choices=[('Passed', 'Passed'), ('Completed', 'Completed'), ('CompletedAndPassed', 'Completed and Passed'), ('NotApplicable', 'Not Applicable')], default='Completed', max_length=20)),
                ('launch_method', models.CharField(choices=[('AnyWindow', 'Any Window'), ('OwnWindow', 'Own Window'), ('NewWindow', 'New Window')], default='AnyWindow', max_length=20)),
                ('launch_parameters', models.JSONField(default=dict)),
                ('au_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cmi5 Assignable Unit',
                'verbose_name_plural': 'cmi5 Assignable Units',
            },
        ),
        migrations.CreateModel(
            name='CMI5Registration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=255)),
                ('launch_token', models.CharField(max_length=500, unique=True)),
                ('launch_url', models.URLField()),
                ('launch_parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMI5Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('launch_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('version', models.CharField(default='1.0.3', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Record Store',
                'verbose_name_plural': 'Learning Record Stores',
            },
        ),
        migrations.CreateModel(
            name='SCORM2004ActivityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=255)),
                ('registration_id', models.UUIDField()),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('not attempted', 'Not Attempted'), ('unknown', 'Unknown')], default='not attempted', max_length=20)),
                ('success_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('progress_measure', models.FloatField(blank=True, null=True)),
                ('completion_threshold', models.FloatField(blank=True, null=True)),
                ('score_scaled', models.FloatField(blank=True, null=True)),
                ('score_raw', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('suspend_data', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=dict)),
                ('interactions', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('first_launch', models.DateTimeField(blank=True, null=True)),
                ('last_launch', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SCORM2004Sequencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=255, unique=True)),
                ('parent_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sequencing_rules', models.JSONField(default=dict)),
                ('rollup_rules', models.JSONField(default=dict)),
                ('navigation_rules', models.JSONField(default=dict)),
                ('objectives', models.JSONField(default=dict)),
                ('objective_rollup_rules', models.JSONField(default=dict)),
                ('completion_threshold', models.FloatField(blank=True, null=True)),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('prerequisites', models.JSONField(default=dict)),
                ('delivery_controls', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SCORM 2004 Sequencing',
                'verbose_name_plural': 'SCORM 2004 Sequencing Rules',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.URLField()),
                ('agent', models.JSONField(default=dict)),
                ('state_id', models.CharField(max_length=255)),
                ('registration', models.UUIDField(blank=True, null=True)),
                ('content', models.JSONField(default=dict)),
                ('content_type', models.CharField(default='application/json', max_length=100)),
                ('etag', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_id', models.CharField(max_length=500, unique=True)),
                ('actor_type', models.CharField(choices=[('Agent', 'Agent'), ('Group', 'Group')], max_length=20)),
                ('actor_mbox', models.EmailField(blank=True, max_length=254)),
                ('actor_mbox_sha1sum', models.CharField(blank=True, max_length=40)),
                ('actor_openid', models.URLField(blank=True)),
                ('actor_account_homepage', models.URLField(blank=True)),
                ('actor_account_name', models.CharField(blank=True, max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('verb_id', models.URLField()),
                ('verb_display', models.JSONField(default=dict)),
                ('object_type', models.CharField(choices=[('Activity', 'Activity'), ('Agent', 'Agent'), ('Group', 'Group'), ('StatementRef', 'StatementRef'), ('SubStatement', 'SubStatement')], max_length=20)),
                ('object_id', models.URLField()),
                ('object_definition_name', models.JSONField(default=dict)),
                ('object_definition_description', models.JSONField(default=dict)),
                ('object_definition_type', models.URLField(blank=True)),
                ('object_definition_more_info', models.URLField(blank=True)),
                ('object_definition_interaction_type', models.CharField(blank=True, max_length=50)),
                ('object_definition_correct_responses_pattern', models.JSONField(default=list)),
                ('object_definition_choices', models.JSONField(default=list)),
                ('object_definition_scale', models.JSONField(default=list)),
                ('object_definition_source', models.JSONField(default=list)),
                ('object_definition_target', models.JSONField(default=list)),
                ('object_definition_steps', models.JSONField(default=list)),
                ('object_definition_extensions', models.JSONField(default=dict)),
                ('result_score_scaled', models.FloatField(blank=True, null=True)),
                ('result_score_raw', models.FloatField(blank=True, null=True)),
                ('result_score_min', models.FloatField(blank=True, null=True)),
                ('result_score_max', models.FloatField(blank=True, null=True)),
                ('result_success', models.BooleanField(blank=True, null=True)),
                ('result_completion', models.BooleanField(blank=True, null=True)),
                ('result_response', models.TextField(blank=True)),
                ('result_duration', models.DurationField(blank=True, null=True)),
                ('result_extensions', models.JSONField(default=dict)),
                ('context_registration', models.UUIDField(blank=True, null=True)),
                ('context_instructor', models.JSONField(default=dict)),
                ('context_team', models.JSONField(default=dict)),
                ('context_context_activities_parent', models.JSONField(default=list)),
                ('context_context_activities_grouping', models.JSONField(default=list)),
                ('context_context_activities_category', models.JSONField(default=list)),
                ('context_context_activities_other', models.JSONField(default=list)),
                ('context_revision', models.CharField(blank=True, max_length=255)),
                ('context_platform', models.CharField(blank=True, max_length=255)),
                ('context_language', models.CharField(blank=True, max_length=10)),
                ('context_statement', models.JSONField(default=dict)),
                ('context_extensions', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stored', models.DateTimeField(auto_now_add=True)),
                ('authority', models.JSONField(default=dict)),
                ('version', models.CharField(default='1.0.3', max_length=20)),
                ('attachments', models.JSONField(default=list)),
                ('raw_statement', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['actor_mbox', 'timestamp'], name='lrs_stateme_actor_m_ab0f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['object_id', 'timestamp'], name='lrs_stateme_object__ab357c_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['verb_id', 'timestamp'], name='lrs_stateme_verb_id_7423a6_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['timestamp'], name='lrs_stateme_timesta_836115_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['activity_id'], name='lrs_state_activit_b31bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['agent'], name='lrs_state_agent_c78b05_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['state_id'], name='lrs_state_state_i_392480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('activity_id', 'agent', 'state_id', 'registration')},
        ),
        migrations.AddField(
            model_name='scorm2004activitystate',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmi5session',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrs.cmi5registration'),
        ),
        migrations.AddField(
            model_name='cmi5registration',
            name='au',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lrs.cmi5au'),
        ),
        migrations.AddField(
            model_name='cmi5registration',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['agent'], name='lrs_agentpr_agent_b31c93_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['profile_id'], name='lrs_agentpr_profile_a051d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentprofile',
            unique_together={('agent', 'profile_id')},
        ),
        migrations.AddIndex(
            model_name='activityprofile',
            index=models.Index(fields=['activity_id'], name='lrs_activit_activit_56f3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityprofile',
            index=models.Index(fields=['profile_id'], name='lrs_activit_profile_3e1957_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityprofile',
            unique_together={('activity_id', 'profile_id')},
        ),
        migrations.AddIndex(
            model_name='scorm2004activitystate',
            index=models.Index(fields=['activity_id'], name='lrs_scorm20_activit_9d4022_idx'),
        ),
        migrations.AddIndex(
            model_name='scorm2004activitystate',
            index=models.Index(fields=['learner'], name='lrs_scorm20_learner_90f7af_idx'),
        ),
        migrations.AddIndex(
            model_name='scorm2004activitystate',
            index=models.Index(fields=['registration_id'], name='lrs_scorm20_registr_033d43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scorm2004activitystate',
            unique_together={('activity_id', 'learner', 'registration_id')},
        ),
        migrations.AddIndex(
            model_name='cmi5session',
            index=models.Index(fields=['registration'], name='lrs_cmi5ses_registr_b12d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='cmi5session',
            index=models.Index(fields=['session_id'], name='lrs_cmi5ses_session_7c416f_idx'),
        ),
        migrations.AddIndex(
            model_name='cmi5session',
            index=models.Index(fields=['is_active'], name='lrs_cmi5ses_is_acti_790f87_idx'),
        ),
        migrations.AddIndex(
            model_name='cmi5registration',
            index=models.Index(fields=['learner'], name='lrs_cmi5reg_learner_07288c_idx'),
        ),
        migrations.AddIndex(
            model_name='cmi5registration',
            index=models.Index(fields=['au'], name='lrs_cmi5reg_au_id_20fd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='cmi5registration',
            index=models.Index(fields=['course_id'], name='lrs_cmi5reg_course__06af51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cmi5registration',
            unique_together={('au', 'learner', 'course_id')},
        ),
    ]
