# Generated by Django 3.2.25 on 2025-10-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='object_type',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Agent', 'Agent'), ('Group', 'Group'), ('StatementRef', 'StatementRef'), ('SubStatement', 'SubStatement')], max_length=20),
        ),
    ]
