# Generated by Django 3.2.25 on 2025-10-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0002_alter_statement_object_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmi5registration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cmi5registration',
            name='au',
        ),
        migrations.RemoveField(
            model_name='cmi5registration',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='cmi5session',
            name='registration',
        ),
        migrations.AlterUniqueTogether(
            name='scorm2004activitystate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scorm2004activitystate',
            name='learner',
        ),
        migrations.DeleteModel(
            name='SCORM2004Sequencing',
        ),
        migrations.DeleteModel(
            name='CMI5AU',
        ),
        migrations.DeleteModel(
            name='CMI5Registration',
        ),
        migrations.DeleteModel(
            name='CMI5Session',
        ),
        migrations.DeleteModel(
            name='SCORM2004ActivityState',
        ),
    ]
