# Generated by Django 4.2.19 on 2025-09-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[("user", "User Group"), ("course", "Course Group")],
                        default="user",
                        help_text="Type of group (user or course)",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "permissions": [
                    ("manage_group", "Can manage group members and settings")
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseGroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_modify",
                    models.BooleanField(
                        default=False,
                        help_text="Whether group members with sufficient permissions can modify the course",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMemberRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_manage_members", models.BooleanField(default=False)),
                ("can_manage_content", models.BooleanField(default=False)),
                (
                    "can_create_topics",
                    models.BooleanField(
                        default=False, help_text="Can create new topics in courses"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auto_enroll",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically enroll users with this role to associated course groups",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="groups.groupmemberrole",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="groups.branchgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "-joined_at"],
            },
        ),
    ]
