# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('branches', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmemberrole',
            name='group',
            field=models.ForeignKey(blank=True, help_text='If null, this is a global role that can be assigned to any group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='groups.branchgroup'),
        ),
        migrations.AddField(
            model_name='coursegroupaccess',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_group_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegroupaccess',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Role to assign to group members for this course access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_accesses', to='groups.groupmemberrole'),
        ),
        migrations.AddField(
            model_name='coursegroupaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_access', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursegroupaccess',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to='groups.branchgroup'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='groups.branchgroup'),
        ),
        migrations.AddField(
            model_name='branchgroup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_groups', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='branchgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmemberrole',
            unique_together={('name', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='coursegroupaccess',
            unique_together={('course', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together={('course', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='branchgroup',
            unique_together={('name', 'branch')},
        ),
    ]
