# Generated by Django 3.2.25 on 2025-10-24 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
