# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '__first__'),
        ('groups', '0003_azure_ad_import_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='azureadgroupimport',
            name='groups_azureadgroupimport_azure_group_id_branch_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='azureadusermapping',
            name='groups_azureadusermapping_azure_user_id_azure_group_import_uniq',
        ),
        migrations.AlterField(
            model_name='azureadgroupimport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='azureadusermapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='azureadgroupimport',
            unique_together={('azure_group_id', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='azureadusermapping',
            unique_together={('azure_user_id', 'azure_group_import')},
        ),
    ]
