# Generated by Django 4.2.19 on 2025-09-23 08:25

import core.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", core.utils.fields.TinyMCEField(blank=True, default="")),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from external message source",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "external_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of external message",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_course_message",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this message is related to a specific course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="message_attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="lms_messages.message",
                    ),
                ),
            ],
        ),
    ]
