# Generated by Django 3.2.25 on 2025-10-17 18:18

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_messages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=core.s3_storage.MediaS3Storage(), upload_to='message_attachments/%Y/%m/%d/'),
        ),
    ]
