# Generated by Django 4.2.19 on 2025-09-23 08:25

import core.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("COURSE_START", "Course Started"),
                            ("COURSE_COMPLETE", "Course Completed"),
                            ("ASSIGNMENT_SUBMIT", "Assignment Submitted"),
                            ("QUIZ_TAKE", "Quiz Taken"),
                            ("FORUM_POST", "Forum Post"),
                            ("RESOURCE_VIEW", "Resource Viewed"),
                            ("CUSTOM", "Custom Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", core.utils.fields.TinyMCEField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic Report"),
                            ("ATTENDANCE", "Attendance Report"),
                            ("PERFORMANCE", "Performance Report"),
                            ("CUSTOM", "Custom Report"),
                            ("specific_users", "Specific Users"),
                            ("learning_progress", "Learning Progress"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True, default=dict, help_text="Report filtering rules"
                    ),
                ),
                (
                    "output_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Fields to include in report output",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="report_attachments/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
