# Generated by Django 3.2.25 on 2025-10-01 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20251001_1548'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_reporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='reports_eve_created_c1e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='reports_eve_type_892127_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user'], name='reports_eve_user_id_c7c89a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['course'], name='reports_eve_course__6215d5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='reportattachment',
            index=models.Index(fields=['uploaded_at'], name='reports_rep_uploade_53c8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportattachment',
            index=models.Index(fields=['file_type'], name='reports_rep_file_ty_d7fa58_idx'),
        ),
    ]
