# Generated by Django 3.2.20 on 2025-10-15 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('overridden', 'Overridden'), ('recalculated', 'Recalculated'), ('imported', 'Imported'), ('exported', 'Exported')], max_length=20)),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, help_text='Previous score value', max_digits=5, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, help_text='New score value', max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('change_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_changes', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Score History',
                'verbose_name_plural': 'Score Histories',
                'db_table': 'score_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(help_text='Operation performed', max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField(help_text='Detailed message')),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='gradebook.scorehistory')),
            ],
            options={
                'verbose_name': 'Score Audit Log',
                'verbose_name_plural': 'Score Audit Logs',
                'db_table': 'score_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['content_type', 'object_id'], name='score_histo_content_a9a3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['changed_by', '-created_at'], name='score_histo_changed_cc1bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['change_type', '-created_at'], name='score_histo_change__0eb303_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreauditlog',
            index=models.Index(fields=['severity', '-created_at'], name='score_audit_severit_1f8b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreauditlog',
            index=models.Index(fields=['operation', '-created_at'], name='score_audit_operati_0d3ce4_idx'),
        ),
    ]