# Generated by Django 3.2.25 on 2025-10-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_auto_20251015_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='scorehistory',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ScoreAuditLog',
        ),
        migrations.DeleteModel(
            name='ScoreHistory',
        ),
    ]
