# Generated by Django 3.2.25 on 2025-10-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '__first__'),
        ('lms_rubrics', '0001_initial'),
        ('courses', '0002_initial'),
        ('discussions', '0002_initial'),
        ('assignments', '0003_initial'),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricoverallfeedback',
            name='created_by',
            field=models.ForeignKey(help_text='The instructor who created this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_rubric_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricoverallfeedback',
            name='discussion',
            field=models.ForeignKey(blank=True, help_text='Related discussion if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_overall_feedback', to='discussions.discussion'),
        ),
        migrations.AddField(
            model_name='rubricoverallfeedback',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, help_text='Related quiz attempt if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_overall_feedback', to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='rubricoverallfeedback',
            name='rubric',
            field=models.ForeignKey(help_text='The rubric this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='overall_feedback', to='lms_rubrics.rubric'),
        ),
        migrations.AddField(
            model_name='rubricoverallfeedback',
            name='student',
            field=models.ForeignKey(help_text='The student who is receiving this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='received_rubric_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricoverallfeedback',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Related assignment submission if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_overall_feedback', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='rubricevaluationhistory',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_history', to='lms_rubrics.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='rubricevaluationhistory',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluation_history', to='discussions.discussion'),
        ),
        migrations.AddField(
            model_name='rubricevaluationhistory',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_evaluation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricevaluationhistory',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_history', to='lms_rubrics.rubricrating'),
        ),
        migrations.AddField(
            model_name='rubricevaluationhistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricevaluationhistory',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluation_history', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='lms_rubrics.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluations', to='discussions.discussion'),
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='lms_rubrics.rubricrating'),
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubricevaluation',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_evaluations', to='assignments.assignmentsubmission'),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='lms_rubrics.rubric'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this rubric belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.course'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rubrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rubricoverallfeedback',
            index=models.Index(fields=['submission', 'student'], name='lms_rubrics_submiss_1d0c61_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricoverallfeedback',
            index=models.Index(fields=['discussion', 'student'], name='lms_rubrics_discuss_88f760_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricoverallfeedback',
            index=models.Index(fields=['conference', 'student'], name='lms_rubrics_confere_d3ffb1_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricoverallfeedback',
            index=models.Index(fields=['quiz_attempt', 'student'], name='lms_rubrics_quiz_at_c5c134_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricoverallfeedback',
            index=models.Index(fields=['rubric', 'student'], name='lms_rubrics_rubric__614acd_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricoverallfeedback',
            index=models.Index(fields=['created_by', '-created_at'], name='lms_rubrics_created_ee8bed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricoverallfeedback',
            unique_together={('submission', 'student'), ('conference', 'student'), ('quiz_attempt', 'student'), ('discussion', 'student')},
        ),
        migrations.AddIndex(
            model_name='rubricevaluationhistory',
            index=models.Index(fields=['submission', 'criterion', '-version'], name='lms_rubrics_submiss_d931ce_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricevaluationhistory',
            index=models.Index(fields=['discussion', 'criterion', 'student', '-version'], name='lms_rubrics_discuss_1d0172_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricevaluation',
            unique_together={('discussion', 'criterion', 'student'), ('submission', 'criterion')},
        ),
    ]
