# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20251111_0047'),
        ('discussions', '0003_auto_20251111_0047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_rubrics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricevaluation',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_evaluations', to='discussions.discussion'),
        ),
        migrations.AlterField(
            model_name='rubricevaluation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rubricevaluation',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_evaluations', to='assignments.assignmentsubmission'),
        ),
    ]
