# Generated by Django 4.2.19 on 2025-05-22 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lms_rubrics", "0004_rubricevaluation_student"),
        ("lms_rubrics", "0005_merge_20250522_1405"),
    ]

    operations = []
