# Generated by Django 3.2.25 on 2025-10-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_rubrics', '0003_alter_rubricevaluation_unique_together'),
        ('lms_rubrics', '0017_alter_rubricoverallfeedback_unique_together_and_more'),
    ]

    operations = [
    ]
