# Generated by Django 3.2.25 on 2025-10-17 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0006_alter_attachment_file'),
        ('assignments', '0037_alter_assignment_attachment'),
        ('lms_rubrics', '0018_merge_20251017_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rubricevaluation',
            unique_together={('submission', 'criterion'), ('discussion', 'criterion', 'student')},
        ),
    ]
