# Generated by Django 3.2.25 on 2025-10-22 00:38

from django.db import migrations, models
import django.db.models.deletion
import scorm.models
import scorm.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearningPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_file', models.FileField(help_text='The e-learning package ZIP file', storage=scorm.storage.SCORMS3Storage(), upload_to=scorm.models.elearning_package_path)),
                ('package_type', models.CharField(choices=[('SCORM_1_2', 'SCORM 1.2'), ('SCORM_2004', 'SCORM 2004'), ('CMI5', 'cmi5'), ('AICC', 'AICC'), ('ARTICULATE', 'Articulate (Storyline/Rise)'), ('CAPTIVATE', 'Adobe Captivate'), ('LECTORA', 'Lectora'), ('ISPRING', 'iSpring'), ('ADOBE_PRESENTER', 'Adobe Presenter')], help_text='The type of e-learning package', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('manifest_path', models.CharField(blank=True, max_length=500)),
                ('launch_file', models.CharField(blank=True, max_length=500)),
                ('extracted_path', models.CharField(blank=True, max_length=500)),
                ('is_extracted', models.BooleanField(default=False)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ELearningTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('not attempted', 'Not Attempted'), ('unknown', 'Unknown')], default='not attempted', max_length=20)),
                ('success_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score_raw', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('score_scaled', models.FloatField(blank=True, null=True)),
                ('progress_measure', models.FloatField(blank=True, null=True)),
                ('completion_threshold', models.FloatField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('suspend_data', models.TextField(blank=True)),
                ('launch_data', models.TextField(blank=True)),
                ('entry', models.CharField(choices=[('ab-initio', 'Ab Initio'), ('resume', 'Resume')], default='ab-initio', max_length=20)),
                ('exit_value', models.CharField(blank=True, choices=[('time-out', 'Time Out'), ('suspend', 'Suspend'), ('logout', 'Logout'), ('normal', 'Normal'), ('ab-initio', 'Ab Initio')], max_length=20)),
                ('credit', models.CharField(choices=[('credit', 'Credit'), ('no-credit', 'No Credit')], default='credit', max_length=20)),
                ('mode', models.CharField(choices=[('browse', 'Browse'), ('normal', 'Normal'), ('review', 'Review')], default='normal', max_length=20)),
                ('learner_preference_audio_level', models.FloatField(blank=True, null=True)),
                ('learner_preference_language', models.CharField(blank=True, max_length=10)),
                ('learner_preference_delivery_speed', models.FloatField(blank=True, null=True)),
                ('learner_preference_audio_captioning', models.BooleanField(blank=True, null=True)),
                ('student_data_mastery_score', models.FloatField(blank=True, null=True)),
                ('student_data_max_time_allowed', models.DurationField(blank=True, null=True)),
                ('student_data_time_limit_action', models.CharField(blank=True, max_length=50)),
                ('objectives', models.JSONField(default=dict, help_text='SCORM objectives data')),
                ('interactions', models.JSONField(default=dict, help_text='SCORM interactions data')),
                ('comments_from_learner', models.JSONField(default=list, help_text='Comments from learner')),
                ('comments_from_lms', models.JSONField(default=list, help_text='Comments from LMS')),
                ('raw_data', models.JSONField(default=dict, help_text='Raw SCORM data from the package')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of attempts made on this SCORM package')),
                ('first_launch', models.DateTimeField(blank=True, null=True)),
                ('last_launch', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SCORMReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('completion', 'Completion Report'), ('performance', 'Performance Report'), ('engagement', 'Engagement Report'), ('detailed', 'Detailed Report')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(default=dict, help_text='Report data and analytics')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_reports', to='courses.course')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
