# Generated by Django 3.2.25 on 2025-10-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scorm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCORMPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_file', models.FileField(help_text='The SCORM package ZIP file', upload_to=scorm.models.elearning_package_path)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('manifest_path', models.CharField(blank=True, max_length=500)),
                ('launch_file', models.CharField(blank=True, max_length=500)),
                ('extracted_path', models.CharField(blank=True, max_length=500)),
                ('is_extracted', models.BooleanField(default=False)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(help_text='The topic this SCORM package belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scorm_package', to='courses.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SCORMReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('completion', 'Completion Report'), ('performance', 'Performance Report'), ('engagement', 'Engagement Report'), ('detailed', 'Detailed Report')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(default=dict, help_text='Report data and analytics')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_reports', to='courses.course')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SCORMTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('not attempted', 'Not Attempted'), ('unknown', 'Unknown')], default='not attempted', max_length=20)),
                ('success_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score_raw', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('score_scaled', models.FloatField(blank=True, null=True)),
                ('progress_measure', models.FloatField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Raw SCORM data from the package')),
                ('first_launch', models.DateTimeField(blank=True, null=True)),
                ('last_launch', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scorm_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='scorm.scormpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'scorm_package')},
            },
        ),
    ]
