# Generated by Django 3.2.25 on 2025-10-16 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scorm.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_auto_20251016_1006'),
        ('scorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearningPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_file', models.FileField(help_text='The e-learning package ZIP file', upload_to=scorm.models.elearning_package_path)),
                ('package_type', models.CharField(choices=[('SCORM_1_2', 'SCORM 1.2'), ('SCORM_2004', 'SCORM 2004'), ('XAPI', 'xAPI (Tin Can)'), ('CMI5', 'cmi5'), ('AICC', 'AICC')], help_text='The type of e-learning package', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('manifest_path', models.CharField(blank=True, max_length=500)),
                ('launch_file', models.CharField(blank=True, max_length=500)),
                ('extracted_path', models.CharField(blank=True, max_length=500)),
                ('xapi_endpoint', models.URLField(blank=True, help_text='xAPI endpoint URL')),
                ('xapi_actor', models.JSONField(blank=True, default=dict, help_text='xAPI actor information')),
                ('cmi5_au_id', models.CharField(blank=True, help_text='cmi5 AU ID', max_length=255)),
                ('cmi5_launch_url', models.URLField(blank=True, help_text='cmi5 launch URL')),
                ('is_extracted', models.BooleanField(default=False)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(help_text='The topic this e-learning package belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='elearning_package', to='courses.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ELearningTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('not attempted', 'Not Attempted'), ('unknown', 'Unknown')], default='not attempted', max_length=20)),
                ('success_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score_raw', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('score_scaled', models.FloatField(blank=True, null=True)),
                ('progress_measure', models.FloatField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Raw SCORM data from the package')),
                ('first_launch', models.DateTimeField(blank=True, null=True)),
                ('last_launch', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elearning_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='scorm.elearningpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'elearning_package')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='scormtracking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scormtracking',
            name='scorm_package',
        ),
        migrations.RemoveField(
            model_name='scormtracking',
            name='user',
        ),
        migrations.DeleteModel(
            name='SCORMPackage',
        ),
        migrations.DeleteModel(
            name='SCORMTracking',
        ),
    ]
