# Generated by Django 3.2.25 on 2025-10-22 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scorm', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='elearning_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='scorm.elearningpackage'),
        ),
        migrations.AddField(
            model_name='elearningtracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_tracking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elearningpackage',
            name='topic',
            field=models.OneToOneField(help_text='The topic this e-learning package belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='elearning_package', to='courses.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='elearningtracking',
            unique_together={('user', 'elearning_package')},
        ),
    ]
