# Generated by Django 3.2.25 on 2025-10-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormattempt',
            name='progress_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Progress percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='interactions_count',
            field=models.IntegerField(default=0, help_text='Number of learner interactions'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='objectives_completed',
            field=models.IntegerField(default=0, help_text='Number of objectives completed'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='objectives_total',
            field=models.IntegerField(default=0, help_text='Total number of objectives'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='current_section',
            field=models.CharField(blank=True, help_text='Current section or page identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='sections_completed',
            field=models.JSONField(default=list, help_text='List of completed section IDs'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='sections_total',
            field=models.IntegerField(default=0, help_text='Total number of sections in the course'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='last_section_progress',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Progress percentage of the last accessed section', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent in seconds'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='first_access',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='last_progress_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
