# Generated by Django 3.2.25 on 2025-10-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0002_auto_20251005_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormattempt',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='interactions_count',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='objectives_completed',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='objectives_total',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='current_section',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='sections_completed',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='sections_total',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='last_section_progress',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='time_spent_seconds',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='session_start_time',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='session_end_time',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='first_access',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='last_progress_update',
        ),
    ]
