# Generated by Django 3.2.25 on 2025-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0004_scormcomment_scorminteraction_scormobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormattempt',
            name='completed_slides',
            field=models.JSONField(default=list, help_text='List of completed slide identifiers'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='detailed_tracking',
            field=models.JSONField(default=dict, help_text='Detailed tracking data including slide visits, time per slide, etc.'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='last_visited_slide',
            field=models.CharField(blank=True, help_text='Last visited slide/page identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='navigation_history',
            field=models.JSONField(default=list, help_text='History of slide navigation with timestamps'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Progress percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_data',
            field=models.JSONField(default=dict, help_text='Current session data including start time, current slide, etc.'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_end_time',
            field=models.DateTimeField(blank=True, help_text='When current session ended', null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_start_time',
            field=models.DateTimeField(blank=True, help_text='When current session started', null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent in seconds for easy calculation'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='total_slides',
            field=models.IntegerField(default=0, help_text='Total number of slides in the course'),
        ),
    ]
