# Generated by Django 3.2.25 on 2025-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0004_auto_20251016_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningtracking',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of attempts made on this SCORM package'),
        ),
    ]
