# Generated by Django 3.2.25 on 2025-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0005_auto_20251006_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormpackage',
            name='version',
            field=models.CharField(choices=[('1.1', 'SCORM 1.1'), ('1.2', 'SCORM 1.2'), ('2004', 'SCORM 2004'), ('xapi', 'xAPI/Tin Can'), ('dual', 'SCORM + xAPI Dual'), ('legacy', 'Legacy SCORM'), ('html5', 'HTML5 Package'), ('storyline', 'Articulate Storyline'), ('captivate', 'Adobe Captivate'), ('lectora', 'Lectora'), ('unknown', 'Unknown Format')], default='1.2', max_length=10),
        ),
    ]
