# Generated by Django 3.2.25 on 2025-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0005_elearningtracking_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningpackage',
            name='package_type',
            field=models.CharField(choices=[('SCORM_1_2', 'SCORM 1.2'), ('SCORM_2004', 'SCORM 2004'), ('XAPI', 'xAPI (Tin Can)'), ('CMI5', 'cmi5'), ('AICC', 'AICC'), ('ARTICULATE', 'Articulate (Storyline/Rise)'), ('CAPTIVATE', 'Adobe Captivate'), ('LECTORA', 'Lectora'), ('ISPRING', 'iSpring'), ('ADOBE_PRESENTER', 'Adobe Presenter')], help_text='The type of e-learning package', max_length=20),
        ),
    ]
