# Generated by Django 3.2.25 on 2025-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0006_alter_scormpackage_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormpackage',
            name='package_file',
            field=models.FileField(help_text='Original SCORM ZIP package', max_length=500, upload_to='scorm_packages/%Y/%m/'),
        ),
    ]
