# Generated by Django 3.2.25 on 2025-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0006_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scormpackage',
            name='scorm_scorm_process_idx',
        ),
        migrations.RemoveIndex(
            model_name='scormpackage',
            name='scorm_scorm_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='scormpackage',
            name='scorm_scorm_version_idx',
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['processing_status', 'created_at'], name='scorm_scorm_process_f400d7_idx'),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['created_by', 'processing_status'], name='scorm_scorm_created_aa8332_idx'),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['version', 'authoring_tool'], name='scorm_scorm_version_949349_idx'),
        ),
    ]
