# Generated by Django 3.2.25 on 2025-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0007_increase_package_file_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent in seconds for easy calculation'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_start_time',
            field=models.DateTimeField(blank=True, help_text='When the current session started', null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_end_time',
            field=models.DateTimeField(blank=True, help_text='When the current session ended', null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='total_slides',
            field=models.IntegerField(default=0, help_text='Total number of slides in the package'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='completed_slides',
            field=models.IntegerField(default=0, help_text='Number of slides completed'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Progress percentage (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='last_visited_slide',
            field=models.CharField(blank=True, help_text='Last slide visited by the user', max_length=255),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='navigation_history',
            field=models.JSONField(blank=True, default=list, help_text='Navigation history through the package'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='detailed_tracking',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed tracking data'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, help_text='Session-specific data'),
        ),
    ]
