# Generated by Django 3.2.25 on 2025-10-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0007_increase_package_file_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormpackage',
            name='package_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic package characteristics: scoring_method, completion_method, package_type, etc.'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='cmi_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete CMI data model storage'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='completed_slides',
            field=models.JSONField(blank=True, default=list, help_text='List of completed slide identifiers'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='detailed_tracking',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed tracking data including slide visits, time per slide, etc.'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='navigation_history',
            field=models.JSONField(blank=True, default=list, help_text='History of slide navigation with timestamps'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, help_text='Current session data including start time, current slide, etc.'),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='mastery_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mastery score from manifest (pass/fail threshold, NOT max score)', max_digits=5, null=True),
        ),
    ]
