# Generated by Django 3.2.25 on 2025-10-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0008_add_scorm_enrollment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormattempt',
            name='session_time',
            field=models.CharField(blank=True, help_text='Session time for this attempt (HH:MM:SS or PTnHnMnS)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='session_time_seconds',
            field=models.IntegerField(default=0, help_text='Session time in seconds for easier querying'),
        ),
        migrations.AddField(
            model_name='scormpackage',
            name='mastery_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mastery score from manifest (cmi.student_data.mastery_score) - percentage 0-100', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scormpackage',
            name='max_time_allowed',
            field=models.CharField(blank=True, help_text='Maximum time allowed from manifest (cmi.student_data.max_time_allowed)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scormpackage',
            name='time_limit_action',
            field=models.CharField(blank=True, help_text='Time limit action from manifest (exit,message / exit,no message / continue,message / continue,no message)', max_length=50, null=True),
        ),
    ]
