# Generated by Django 3.2.25 on 2025-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0008_auto_20251022_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormattempt',
            name='completed_slides',
            field=models.IntegerField(default=0, help_text='Number of completed slides'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='detailed_tracking',
            field=models.JSONField(default=dict, help_text='Detailed tracking data including slide visits, time per slide, etc.'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='last_visited_slide',
            field=models.CharField(blank=True, help_text='Last visited slide/page identifier', max_length=800),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='navigation_history',
            field=models.JSONField(default=list, help_text='History of slide navigation with timestamps'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='session_data',
            field=models.JSONField(default=dict, help_text='Current session data including start time, current slide, etc.'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='session_end_time',
            field=models.DateTimeField(blank=True, help_text='When current session ended', null=True),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='session_start_time',
            field=models.DateTimeField(blank=True, help_text='When current session started', null=True),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='total_slides',
            field=models.IntegerField(default=0, help_text='Total number of slides in the course'),
        ),
        migrations.AlterField(
            model_name='scormcomment',
            name='location',
            field=models.CharField(blank=True, help_text='Location where comment was made', max_length=800),
        ),
        migrations.AlterField(
            model_name='scorminteraction',
            name='interaction_id',
            field=models.CharField(help_text='Unique identifier for the interaction', max_length=800),
        ),
        migrations.AlterField(
            model_name='scormobjective',
            name='objective_id',
            field=models.CharField(help_text='Unique identifier for the objective', max_length=800),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='extracted_path',
            field=models.CharField(help_text='Path to extracted SCORM content', max_length=800),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='identifier',
            field=models.CharField(help_text='Package identifier from manifest', max_length=800),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='launch_url',
            field=models.CharField(help_text='Relative path to launch file (index.html, story.html, etc.)', max_length=800),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='package_file',
            field=models.FileField(help_text='Original SCORM ZIP package', max_length=800, upload_to='scorm_packages/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='scormpackage',
            name='title',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
