# Generated by Django 3.2.25 on 2025-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0006_alter_elearningpackage_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearningpackage',
            name='cmi5_au_id',
        ),
        migrations.RemoveField(
            model_name='elearningpackage',
            name='cmi5_launch_url',
        ),
        migrations.AlterField(
            model_name='elearningpackage',
            name='package_type',
            field=models.CharField(choices=[('SCORM_1_2', 'SCORM 1.2'), ('SCORM_2004', 'SCORM 2004'), ('XAPI', 'xAPI (Tin Can)')], help_text='The type of e-learning package', max_length=20),
        ),
    ]
