# Generated by Django 3.2.25 on 2025-10-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0009_increase_char_limits_to_800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormattempt',
            name='detailed_tracking',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed tracking data including slide visits, time per slide, etc.'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='navigation_history',
            field=models.JSONField(blank=True, default=list, help_text='History of slide navigation with timestamps'),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, help_text='Current session data including start time, current slide, etc.'),
        ),
    ]
