# Generated by Django 3.2.25 on 2025-10-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0010_alter_elearningpackage_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearningpackage',
            name='xapi_actor',
        ),
        migrations.RemoveField(
            model_name='elearningpackage',
            name='xapi_endpoint',
        ),
        migrations.RemoveField(
            model_name='elearningpackage',
            name='xapi_password',
        ),
        migrations.RemoveField(
            model_name='elearningpackage',
            name='xapi_username',
        ),
        migrations.AlterField(
            model_name='elearningpackage',
            name='package_type',
            field=models.CharField(choices=[('SCORM_1_2', 'SCORM 1.2'), ('SCORM_2004', 'SCORM 2004'), ('CMI5', 'cmi5'), ('AICC', 'AICC'), ('ARTICULATE', 'Articulate (Storyline/Rise)'), ('CAPTIVATE', 'Adobe Captivate'), ('LECTORA', 'Lectora'), ('ISPRING', 'iSpring'), ('ADOBE_PRESENTER', 'Adobe Presenter')], help_text='The type of e-learning package', max_length=20),
        ),
    ]
