# Generated by Django 3.2.25 on 2025-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0010_fix_json_field_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormattempt',
            name='cmi_data_history',
            field=models.JSONField(blank=True, default=list, help_text='Complete history of CMI data changes with timestamps'),
        ),
    ]
