# Generated by Django 3.2.25 on 2025-10-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0011_add_cmi_data_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormattempt',
            name='completed_slides',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='detailed_tracking',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='last_visited_slide',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='navigation_history',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='session_data',
        ),
        migrations.RemoveField(
            model_name='scormattempt',
            name='total_slides',
        ),
    ]
