# Generated by Django 3.2.25 on 2025-10-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0012_remove_custom_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormattempt',
            name='score_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='score_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='session_time',
            field=models.CharField(blank=True, help_text='Session time in SCORM format', max_length=50),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='time_spent_seconds',
            field=models.IntegerField(blank=True, help_text='Total time spent in seconds for easy calculation', null=True),
        ),
        migrations.AlterField(
            model_name='scormattempt',
            name='total_time',
            field=models.CharField(blank=True, help_text='Total time in SCORM format (hhhh:mm:ss.ss)', max_length=50),
        ),
    ]
