# Generated by Django 3.2.25 on 2025-10-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0013_remove_hardcoded_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormpackage',
            name='has_score_requirement',
            field=models.BooleanField(default=True, help_text='Whether this SCORM content requires a passing score to be marked complete'),
        ),
    ]
