# Generated by Django 3.2.25 on 2025-10-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0017_add_complete_cmi_xapi_fields'),
        ('scorm', '0017_remove_scorm_objective_and_comment_tables'),
    ]

    operations = [
    ]
