# Generated by Django 3.2.25 on 2025-11-11 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='discussions/attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='discussions.comment')),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='discussions.discussion')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Attachment',
                'verbose_name_plural': 'Discussion Attachments',
                'db_table': 'discussions_attachment',
            },
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddIndex(
            model_name='discussionattachment',
            index=models.Index(fields=['discussion'], name='discussions_discuss_beb012_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionattachment',
            index=models.Index(fields=['comment'], name='discussions_comment_8b5d52_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionattachment',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='discussions_uploade_7d4840_idx'),
        ),
        migrations.AddConstraint(
            model_name='discussionattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('comment__isnull', True), ('discussion__isnull', False)), models.Q(('comment__isnull', False), ('discussion__isnull', True)), _connector='OR'), name='discussions_attachment_exclusive_parent'),
        ),
    ]
