# Generated by Django 3.2.25 on 2025-10-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_discussion_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('ilt_conference', 'ILT/Conference'), ('discussion', 'Discussion')], default='discussion', max_length=20),
        ),
    ]
