# Generated by Django 3.2.25 on 2025-10-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_alter_discussion_assessment_type'),
    ]

    operations = [
    ]
