# Generated by Django 3.2.25 on 2025-10-17 18:18

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_alter_discussion_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=core.s3_storage.MediaS3Storage(), upload_to='discussions/attachments/%Y/%m/%d/'),
        ),
    ]
